import { createElement } from 'react'
import { renderToStaticMarkup } from 'react-dom/server'
import { describe, expect, it } from 'vitest'
import { HodView } from '../src/pages/hod-pages'

describe('HodView', () => {
  it('renders live proof provenance instead of the old placeholder copy', () => {
    const markup = renderToStaticMarkup(createElement(HodView, {
      onOpenQueueHistory: () => {},
      onOpenStudentShell: () => {},
      onOpenRiskExplorer: () => {},
      onOpenCourse: () => {},
      onOpenStudent: () => {},
      tasks: [],
      calendarAuditEvents: [],
      loading: false,
      error: '',
      summary: {
        activeRunContext: {
          simulationRunId: 'run_001',
          batchId: 'batch_001',
          batchLabel: '2023 Mathematics and Computing',
          branchName: 'B.Tech Mathematics and Computing',
          runLabel: 'Proof Run 1',
          status: 'active',
          seed: 42,
          createdAt: '2026-03-16T00:00:00.000Z',
          sourceLabel: 'Live proof records',
          checkpointContext: {
            simulationStageCheckpointId: 'checkpoint_001',
            simulationRunId: 'run_001',
            semesterNumber: 6,
            stageKey: 'post-tt1',
            stageLabel: 'Post TT1',
            stageDescription: 'First major risk checkpoint after TT1 evidence lands and the first queue decision is made.',
            stageOrder: 2,
            previousCheckpointId: 'checkpoint_000',
            nextCheckpointId: 'checkpoint_002',
          },
        },
        scope: {
          departmentNames: ['School of Computing'],
          branchNames: ['Mathematics and Computing'],
        },
        monitoringSummary: {
          riskAssessmentCount: 24,
          activeReassessmentCount: 8,
          alertDecisionCount: 8,
          acknowledgementCount: 3,
          resolutionCount: 2,
        },
        totals: {
          studentsCovered: 120,
          highRiskCount: 12,
          mediumRiskCount: 18,
          averageQueueAgeHours: 21.5,
          manualOverrideCount: 1,
          unresolvedAlertCount: 5,
          resolvedAlertCount: 2,
        },
        sectionComparison: [
          { sectionCode: 'A', studentCount: 60, highRiskCount: 5, mediumRiskCount: 8, averageAttendancePct: 81, openReassessmentCount: 4 },
          { sectionCode: 'B', studentCount: 60, highRiskCount: 7, mediumRiskCount: 10, averageAttendancePct: 76, openReassessmentCount: 4 },
        ],
        semesterRiskDistribution: [
          { semesterNumber: 1, highPressureCount: 6, reviewCount: 12, stableCount: 102, basis: 'transcript-backlog' },
          { semesterNumber: 6, highPressureCount: 12, reviewCount: 18, stableCount: 90, basis: 'transcript-backlog' },
        ],
        backlogDistribution: [
          { bucket: '0', studentCount: 84 },
          { bucket: '1', studentCount: 22 },
          { bucket: '2', studentCount: 9 },
          { bucket: '3+', studentCount: 5 },
        ],
        electiveDistribution: [
          { stream: 'Data Intelligence', recommendationCount: 42 },
        ],
        facultyLoadSummary: {
          facultyCount: 10,
          overloadedFacultyCount: 2,
          averageWeeklyContactHours: 13.6,
        },
      },
      courseRollups: [
        {
          courseCode: 'MC601',
          title: 'Graph Theory',
          sectionCodes: ['A', 'B'],
          riskCountHigh: 6,
          riskCountMedium: 8,
          averageAttendancePct: 79,
          tt1WeakCount: 11,
          tt2WeakCount: 8,
          seeWeakCount: 5,
          weakQuestionSignalCount: 7,
          backlogCarryoverCount: 4,
          openReassessmentCount: 5,
          resolvedReassessmentCount: 2,
          studentCount: 120,
        },
      ],
      facultyRollups: [
        {
          facultyId: 'mnc_t1',
          facultyName: 'Dr. Devika Shetty',
          designation: 'Professor',
          permissions: ['HOD', 'MENTOR', 'COURSE_LEADER'],
          weeklyContactHours: 15,
          sectionLoadCount: 2,
          assignedSections: ['A', 'B'],
          queueLoad: 8,
          avgAcknowledgementLagHours: 10.2,
          reassessmentClosureRate: 45,
          interventionCount: 6,
          overloadFlag: true,
        },
      ],
      studentWatchRows: [
        {
          studentId: 'mnc_student_001',
          studentName: 'Aarav Sharma',
          usn: '1MS23MC001',
          sectionCode: 'A',
          currentSemester: 6,
          currentRiskBand: 'High',
          currentRiskProbScaled: 82,
          primaryCourseCode: 'MC601',
          primaryCourseTitle: 'Graph Theory',
          currentReassessmentStatus: 'Open',
          nextDueAt: '2026-03-18T09:00:00.000Z',
          observedEvidence: {
            attendancePct: 68,
            tt1Pct: 34,
            tt2Pct: 41,
            quizPct: 52,
            assignmentPct: 61,
            seePct: 46,
            cgpa: 6.74,
            backlogCount: 2,
            weakCoCount: 2,
            weakQuestionCount: 4,
            interventionRecoveryStatus: 'watch',
          },
          electiveFit: {
            recommendedCode: 'MC6E01',
            recommendedTitle: 'Applied Optimization',
            stream: 'Data Intelligence',
            rationale: ['Stable math signal', 'Moderate programming readiness'],
            alternatives: [],
          },
          courseSnapshots: [
            {
              riskAssessmentId: 'risk_001',
              offeringId: 'off_001',
              courseCode: 'MC601',
              courseTitle: 'Graph Theory',
              sectionCode: 'A',
              riskBand: 'High',
              riskProbScaled: 82,
              recommendedAction: 'Reassessment',
              observedEvidence: {
                attendancePct: 68,
                tt1Pct: 34,
                tt2Pct: 41,
                quizPct: 52,
                assignmentPct: 61,
                seePct: 46,
                cgpa: 6.74,
                backlogCount: 2,
                weakCoCount: 2,
                weakQuestionCount: 4,
                interventionRecoveryStatus: 'watch',
              },
              drivers: [
                { label: 'Attendance below threshold', impact: 0.4, feature: 'attendancePct' },
              ],
            },
          ],
          evidenceTimeline: [
            {
              studentObservedSemesterStateId: 'evidence_001',
              semesterNumber: 1,
              termId: 'term_1',
              sectionCode: 'A',
              observedState: { riskBand: 'Low' },
              createdAt: '2026-03-16T00:00:00.000Z',
              updatedAt: '2026-03-16T00:00:00.000Z',
            },
            {
              studentObservedSemesterStateId: 'evidence_006',
              semesterNumber: 6,
              termId: 'term_6',
              sectionCode: 'A',
              observedState: { riskBand: 'High', evidenceWindowCount: 2, riskBands: ['High'] },
              createdAt: '2026-03-16T00:00:00.000Z',
              updatedAt: '2026-03-16T00:00:00.000Z',
            },
          ],
        },
      ],
      reassessmentRows: [
        {
          reassessmentEventId: 'reassessment_001',
          simulationRunId: 'run_001',
          runLabel: 'Proof Run 1',
          studentId: 'mnc_student_001',
          studentName: 'Aarav Sharma',
          usn: '1MS23MC001',
          courseCode: 'MC601',
          courseTitle: 'Graph Theory',
          sectionCode: 'A',
          assignedToRole: 'MENTOR',
          dueAt: '2026-03-18T09:00:00.000Z',
          status: 'Open',
          riskBand: 'High',
          riskProbScaled: 82,
          decisionType: 'reassess',
          decisionNote: 'Observed performance remains below safe threshold.',
          acknowledgement: null,
          resolution: null,
        },
      ],
    }))

    expect(markup).toContain('Live HoD Analytics')
    expect(markup).toContain('data-proof-surface="hod-proof-analytics"')
    expect(markup).toContain('sourced from live proof records')
    expect(markup).toContain('Post TT1')
    expect(markup).toContain('Course Hotspots')
    expect(markup).toContain('TT Window')
    expect(markup).toContain('34% / 41%')
    expect(markup).not.toContain('HoD Proof Boundary')
  })

  it('defaults Action Needed to governed open cases instead of raw watch bands', () => {
    const markup = renderToStaticMarkup(createElement(HodView, {
      onOpenQueueHistory: () => {},
      onOpenStudentShell: () => {},
      onOpenRiskExplorer: () => {},
      onOpenCourse: () => {},
      onOpenStudent: () => {},
      tasks: [],
      calendarAuditEvents: [],
      loading: false,
      error: '',
      summary: {
        activeRunContext: {
          simulationRunId: 'run_001',
          batchId: 'batch_001',
          batchLabel: '2023 Mathematics and Computing',
          branchName: 'B.Tech Mathematics and Computing',
          runLabel: 'Proof Run 1',
          status: 'active',
          seed: 42,
          createdAt: '2026-03-16T00:00:00.000Z',
          sourceLabel: 'Live proof records',
          checkpointContext: {
            simulationStageCheckpointId: 'checkpoint_001',
            simulationRunId: 'run_001',
            semesterNumber: 6,
            stageKey: 'post-tt1',
            stageLabel: 'Post TT1',
            stageDescription: 'Checkpoint',
            stageOrder: 2,
            previousCheckpointId: 'checkpoint_000',
            nextCheckpointId: 'checkpoint_002',
          },
        },
        scope: {
          departmentNames: ['School of Computing'],
          branchNames: ['Mathematics and Computing'],
        },
        monitoringSummary: {
          riskAssessmentCount: 2,
          activeReassessmentCount: 1,
          alertDecisionCount: 1,
          acknowledgementCount: 0,
          resolutionCount: 0,
        },
        totals: {
          studentsCovered: 2,
          highRiskCount: 1,
          mediumRiskCount: 0,
          averageQueueAgeHours: 0,
          manualOverrideCount: 0,
          unresolvedAlertCount: 1,
          resolvedAlertCount: 0,
        },
        sectionComparison: [],
        semesterRiskDistribution: [],
        backlogDistribution: [],
        electiveDistribution: [],
        facultyLoadSummary: {
          facultyCount: 1,
          overloadedFacultyCount: 0,
          averageWeeklyContactHours: 10,
        },
      },
      courseRollups: [],
      facultyRollups: [],
      studentWatchRows: [
        {
          studentId: 'student_open_low',
          studentName: 'Open Low Risk',
          usn: '1MS23MC010',
          sectionCode: 'A',
          currentSemester: 6,
          currentRiskBand: 'Low',
          currentRiskProbScaled: 24,
          primaryCourseCode: 'MC601',
          primaryCourseTitle: 'Graph Theory',
          currentReassessmentStatus: 'Open',
          nextDueAt: '2026-03-18T09:00:00.000Z',
          observedEvidence: {
            attendancePct: 76,
            tt1Pct: 48,
            tt2Pct: 52,
            quizPct: 60,
            assignmentPct: 64,
            seePct: 58,
            cgpa: 7.2,
            backlogCount: 0,
            weakCoCount: 1,
            weakQuestionCount: 1,
            interventionRecoveryStatus: 'watch',
          },
          electiveFit: null,
          courseSnapshots: [],
          evidenceTimeline: [],
        },
        {
          studentId: 'student_watch_high',
          studentName: 'Watching High Risk',
          usn: '1MS23MC011',
          sectionCode: 'A',
          currentSemester: 6,
          currentRiskBand: 'High',
          currentRiskProbScaled: 81,
          primaryCourseCode: 'MC601',
          primaryCourseTitle: 'Graph Theory',
          currentReassessmentStatus: 'Watching',
          nextDueAt: '2026-03-19T09:00:00.000Z',
          observedEvidence: {
            attendancePct: 61,
            tt1Pct: 34,
            tt2Pct: 39,
            quizPct: 44,
            assignmentPct: 50,
            seePct: 42,
            cgpa: 6.4,
            backlogCount: 1,
            weakCoCount: 3,
            weakQuestionCount: 4,
            interventionRecoveryStatus: 'watch',
          },
          electiveFit: null,
          courseSnapshots: [],
          evidenceTimeline: [],
        },
      ],
      reassessmentRows: [],
    }))

    expect(markup).toContain('Open Low Risk')
    expect(markup).not.toContain('Watching High Risk')
    expect((markup.match(/Acknowledge/g) ?? []).length).toBe(1)
  })

  it('renders an explicit empty watchlist message instead of phantom rows', () => {
    const markup = renderToStaticMarkup(createElement(HodView, {
      onOpenQueueHistory: () => {},
      onOpenStudentShell: () => {},
      onOpenRiskExplorer: () => {},
      onOpenCourse: () => {},
      onOpenStudent: () => {},
      tasks: [],
      calendarAuditEvents: [],
      loading: false,
      error: '',
      summary: {
        activeRunContext: {
          simulationRunId: 'run_001',
          batchId: 'batch_001',
          batchLabel: '2023 Mathematics and Computing',
          branchName: 'B.Tech Mathematics and Computing',
          runLabel: 'Proof Run 1',
          status: 'active',
          seed: 42,
          createdAt: '2026-03-16T00:00:00.000Z',
          sourceLabel: 'Live proof records',
          checkpointContext: null,
        },
        scope: {
          departmentNames: ['Computer Science and Engineering'],
          branchNames: ['Mathematics and Computing'],
        },
        monitoringSummary: {
          riskAssessmentCount: 0,
          activeReassessmentCount: 0,
          alertDecisionCount: 0,
          acknowledgementCount: 0,
          resolutionCount: 0,
        },
        totals: {
          studentsCovered: 0,
          highRiskCount: 0,
          mediumRiskCount: 0,
          averageQueueAgeHours: 0,
          manualOverrideCount: 0,
          unresolvedAlertCount: 0,
          resolvedAlertCount: 0,
        },
        sectionComparison: [],
        semesterRiskDistribution: [],
        backlogDistribution: [],
        electiveDistribution: [],
        facultyLoadSummary: {
          facultyCount: 0,
          overloadedFacultyCount: 0,
          averageWeeklyContactHours: 0,
        },
      },
      courseRollups: [],
      facultyRollups: [],
      studentWatchRows: [],
      reassessmentRows: [],
    }))

    expect(markup).toContain('No students are in the current HoD watchlist for this scope.')
    expect(markup).not.toContain('Acknowledge')
  })
})
