// @vitest-environment jsdom
import { createElement } from 'react'
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { renderToStaticMarkup } from 'react-dom/server'
import { afterEach, describe, expect, it, vi } from 'vitest'
import type {
  ApiProofDashboard,
  ApiProofRunCheckpointDetail,
  ApiSimulationStageCheckpointSummary,
} from '../src/api/types'
import { SystemAdminProofDashboardWorkspace } from '../src/system-admin-proof-dashboard-workspace'
import { getAccessiblePrimaryAccent } from '../src/ui-primitives'

afterEach(() => {
  cleanup()
  if (typeof window !== 'undefined') {
    window.sessionStorage.clear()
  }
})

function buildCheckpoint(overrides?: Partial<ApiSimulationStageCheckpointSummary>): ApiSimulationStageCheckpointSummary {
  return {
    simulationStageCheckpointId: 'checkpoint_post_tt1',
    simulationRunId: 'run_001',
    semesterNumber: 6,
    stageKey: 'post-tt1',
    stageLabel: 'Post TT1',
    stageDescription: 'First major risk checkpoint after TT1 evidence lands and the first queue decision is made.',
    stageOrder: 2,
    previousCheckpointId: 'checkpoint_pre_tt1',
    nextCheckpointId: 'checkpoint_post_tt2',
    totalStudentProjectionCount: 24,
    highRiskCount: 8,
    mediumRiskCount: 10,
    lowRiskCount: 6,
    openQueueCount: 5,
    watchQueueCount: 2,
    resolvedQueueCount: 1,
    watchStudentCount: 2,
    blockingQueueItemCount: 5,
    noActionHighRiskCount: 11,
    averageRiskDeltaScaled: 4,
    averageRiskChangeFromPreviousCheckpointScaled: 4,
    averageCounterfactualLiftScaled: 7,
    stageAdvanceBlocked: true,
    playbackAccessible: false,
    blockedByCheckpointId: 'checkpoint_post_tt1',
    blockedProgressionReason: 'Queue items from the TT1 checkpoint are still unresolved.',
    ...overrides,
  }
}

describe('SystemAdminProofDashboardWorkspace', () => {
  it('renders queue diagnostics, checkpoint readiness, and blocked-stage reasoning', () => {
    const selectedCheckpoint = buildCheckpoint()
    const checkpoints = [
      buildCheckpoint({
        simulationStageCheckpointId: 'checkpoint_pre_tt1',
        stageKey: 'pre-tt1',
        stageLabel: 'Pre TT1',
        stageOrder: 1,
        previousCheckpointId: null,
        nextCheckpointId: selectedCheckpoint.simulationStageCheckpointId,
        stageAdvanceBlocked: false,
        playbackAccessible: true,
        blockedByCheckpointId: null,
        blockedProgressionReason: null,
        openQueueCount: 0,
        blockingQueueItemCount: 0,
      }),
      selectedCheckpoint,
    ]

    const checkpointDetail: ApiProofRunCheckpointDetail = {
      checkpoint: selectedCheckpoint,
      queuePreview: [],
      offeringRollups: [],
    }

    const proofDashboard: ApiProofDashboard = {
      imports: [{
        curriculumImportVersionId: 'import_001',
        sourceLabel: 'MSRUAS workbook',
        sourceChecksum: 'source-sha',
        outputChecksum: 'output-sha',
        compilerVersion: 'compiler-v1',
        validationStatus: 'valid',
        unresolvedMappingCount: 0,
        status: 'approved',
        approvedAt: '2026-03-16T00:00:00.000Z',
        createdAt: '2026-03-16T00:00:00.000Z',
        certificate: {},
      }],
      latestValidation: {
        validatorVersion: 'validator-v1',
        status: 'valid',
        summary: {},
      },
      crosswalkReviewQueue: [],
      proofRuns: [{
        simulationRunId: 'run_001',
        runLabel: 'Proof Run 1',
        status: 'active',
        activeFlag: true,
        seed: 42,
        createdAt: '2026-03-16T00:00:00.000Z',
        startedAt: '2026-03-16T00:00:00.000Z',
        completedAt: null,
        failureCode: null,
        failureMessage: null,
        progress: { phase: 'running', percent: 68 },
        metrics: {},
        queueAgeSeconds: 180,
        leaseState: 'leased',
        leaseExpiresAt: '2026-03-16T00:15:00.000Z',
        retryState: null,
        retryOfSimulationRunId: null,
        failureState: 'none',
      }],
      activeRunDetail: {
        simulationRunId: 'run_001',
        runLabel: 'Proof Run 1',
        seed: 42,
        activeOperationalSemester: 6,
        createdAt: '2026-03-16T00:00:00.000Z',
        startedAt: '2026-03-16T00:00:00.000Z',
        completedAt: null,
        status: 'active',
        failureCode: null,
        failureMessage: null,
        progress: { phase: 'running', percent: 68 },
        monitoringSummary: {
          riskAssessmentCount: 24,
          activeReassessmentCount: 5,
          alertDecisionCount: 6,
          acknowledgementCount: 2,
          resolutionCount: 1,
        },
        coverageDiagnostics: {
          behaviorProfileCoverage: { count: 120, expected: 120 },
          topicStateCoverage: { count: 640 },
          coStateCoverage: { count: 310 },
          questionTemplateCoverage: { count: 84 },
          questionResultCoverage: { count: 2400 },
          interventionResponseCoverage: { count: 36 },
          worldContextCoverage: { count: 12 },
        },
        modelDiagnostics: {
          featureRowCount: 2400,
          activeRunFeatureRowCount: 360,
          sourceRunCount: 5,
          runtimeSummary: {},
          overallCourseRuntimeSummary: {},
          queueBurdenSummary: {},
          stageRollups: [],
          acceptanceGateSummary: {},
          splitSummary: { train: 1800, validation: 300, test: 300 },
          worldSplitSummary: { train: 4, validation: 1, test: 1 },
          scenarioFamilySummary: { steady: 3, rescue: 2 },
          headSupportSummary: { overallCourseRisk: { positives: 1200 } },
          calibrationVersion: 'isotonic-v1',
          policyDiagnostics: { gates: 'ok' },
          coEvidenceDiagnostics: { mode: 'graph-aware' },
          uiParityDiagnostics: { facultySurface: 'aligned' },
          production: {
            artifactVersion: 'artifact-v1',
            modelFamily: 'observable',
            createdAt: '2026-03-16T00:00:00.000Z',
            evaluation: { auc: 0.84, support: 'healthy' },
            trainingManifestVersion: 'manifest-v1',
            splitSummary: { train: 1800, validation: 300, test: 300 },
            worldSplitSummary: { train: 4, validation: 1, test: 1 },
            scenarioFamilySummary: { steady: 3, rescue: 2 },
            headSupportSummary: { overallCourseRisk: { positives: 1200 } },
            calibrationVersion: 'isotonic-v1',
            policyDiagnostics: { gates: 'ok' },
            coEvidenceDiagnostics: { mode: 'graph-aware' },
            uiParityDiagnostics: { facultySurface: 'aligned' },
            correlations: { attendancePct: 0.41 },
          },
          challenger: null,
          correlations: { attendancePct: 0.41 },
        },
        queueDiagnostics: {
          queuedRunCount: 1,
          runningRunCount: 1,
          failedRunCount: 0,
          retryableRunCount: 0,
          retryInFlightCount: 0,
          oldestQueuedRunAgeSeconds: 180,
          expiredLeaseRunCount: 0,
        },
        workerDiagnostics: {
          queueAgeSeconds: 180,
          leaseState: 'leased',
          leaseExpiresAt: '2026-03-16T00:15:00.000Z',
          retryState: null,
          retryOfSimulationRunId: null,
          failureState: 'none',
          progressPhase: 'checkpoint-playback',
          progressPercent: 68,
        },
        checkpointReadiness: {
          totalCheckpointCount: checkpoints.length,
          readyCheckpointCount: 1,
          blockedCheckpointCount: 1,
          playbackBlockedCheckpointCount: 1,
          totalBlockingQueueItemCount: 5,
          firstBlockedCheckpointId: selectedCheckpoint.simulationStageCheckpointId,
          lastReadyCheckpointId: 'checkpoint_pre_tt1',
        },
        teacherAllocationLoad: [],
        queuePreview: [],
        snapshots: [{
          simulationResetSnapshotId: 'snapshot_001',
          snapshotLabel: 'Baseline snapshot',
          createdAt: '2026-03-16T00:00:00.000Z',
          payload: {},
        }],
        checkpoints,
      },
      lifecycleAudit: [],
      recentOperationalEvents: [{
        operationalTelemetryEventId: 'ops_evt_001',
        source: 'backend',
        name: 'startup.ready',
        level: 'info',
        timestamp: '2026-03-16T00:00:00.000Z',
        details: {
          host: '0.0.0.0',
          sessionCookieSecure: true,
        },
        createdAt: '2026-03-16T00:00:00.000Z',
      }],
    }

    const markup = renderToStaticMarkup(createElement(SystemAdminProofDashboardWorkspace, {
      proofDashboard,
      proofDashboardLoading: false,
      activeRunCheckpoints: checkpoints,
      activeModelDiagnostics: { scenarioFamilySummary: { steady: 3, rescue: 2 } },
      activeProductionDiagnostics: {
        artifactVersion: 'artifact-v1',
        evaluation: { auc: 0.84, support: 'healthy' },
        correlations: { attendancePct: 0.41 },
      },
      activeDiagnosticsTrainingManifestVersion: 'manifest-v1',
      activeDiagnosticsCalibrationVersion: 'isotonic-v1',
      activeDiagnosticsSplitSummary: { train: 1800, validation: 300, test: 300 },
      activeDiagnosticsWorldSplitSummary: { train: 4, validation: 1, test: 1 },
      activeDiagnosticsScenarioFamilies: { steady: 3, rescue: 2 },
      activeDiagnosticsHeadSupportSummary: { overallCourseRisk: { positives: 1200 } },
      activeDiagnosticsGovernedRunCount: 5,
      activeDiagnosticsSkippedRunCount: 0,
      activeDiagnosticsDisplayProbabilityAllowed: false,
      activeDiagnosticsSupportWarning: 'Held-out positive support is below the probability display threshold.',
      activeDiagnosticsPolicyDiagnostics: { gates: 'ok' },
      activeDiagnosticsCoEvidence: { mode: 'graph-aware' },
      activeDiagnosticsPolicyAcceptance: { policy: 'accepted' },
      activeDiagnosticsOverallCourseRuntime: { parity: 'aligned' },
      activeDiagnosticsQueueBurden: { mentor: 2 },
      activeDiagnosticsUiParity: { facultySurface: 'aligned' },
      selectedProofCheckpoint: selectedCheckpoint,
      selectedProofCheckpointDetail: checkpointDetail,
      selectedProofCheckpointBlocked: true,
      selectedProofCheckpointHasBlockedProgression: true,
      selectedProofCheckpointCanStepForward: false,
      selectedProofCheckpointCanPlayToEnd: false,
      proofPlaybackRestoreNotice: {
        tone: 'neutral',
        message: 'Proof playback restored to Semester 6 · Post TT1. Use Reset playback to clear the saved checkpoint.',
      },
      onCreateProofImport: () => {},
      onValidateLatestProofImport: () => {},
      onReviewPendingCrosswalks: () => {},
      onApproveLatestProofImport: () => {},
      onCreateProofRun: () => {},
      onRecomputeProofRunRisk: () => {},
      onActivateProofRun: () => {},
      onActivateProofSemester: () => {},
      onRetryProofRun: () => {},
      onArchiveProofRun: () => {},
      onRestoreProofSnapshot: () => {},
      onResetProofPlaybackSelection: () => {},
      onSelectProofCheckpoint: () => {},
      onStepProofPlayback: () => {},
      formatSplitSummary: summary => JSON.stringify(summary),
      formatKeyedCounts: summary => JSON.stringify(summary),
      formatHeadSupportSummary: summary => JSON.stringify(summary),
      formatDiagnosticSummary: summary => JSON.stringify(summary),
    }))

    expect(markup).toContain('Current Proof State')
    expect(markup).toContain('Selected Checkpoint')
    expect(markup).toContain('Action Pressure')
    expect(markup).toContain('Queue Health')
    expect(markup).toContain('Checkpoint Readiness')
    expect(markup).toContain('Worker Lease')
    expect(markup).toContain('data-proof-shell="shared"')
    expect(markup).toContain('data-proof-launcher="floating"')
    expect(markup).toContain('data-proof-action="proof-shell-launcher"')
    expect(markup).toContain('Checkpoint-bound proof counts')
    expect(markup).toContain('Proof workflow rail')
    expect(markup).toContain('Operational semester')
    expect(markup).toContain('Semester 6')
    expect(markup).toContain('Selected checkpoint: semester 6')
    expect(markup).toContain('Proof playback restored')
    expect(markup).toContain('Reset playback')
    expect(markup).toContain('Scope details')
    expect(markup).not.toContain('Operations Preview')

    const { container: checkpointContainer } = render(createElement(SystemAdminProofDashboardWorkspace, {
      proofDashboard,
      proofDashboardLoading: false,
      initialActiveDashboardTab: 'checkpoint',
      activeRunCheckpoints: checkpoints,
      activeModelDiagnostics: { scenarioFamilySummary: { steady: 3, rescue: 2 } },
      activeProductionDiagnostics: {
        artifactVersion: 'artifact-v1',
        evaluation: { auc: 0.84, support: 'healthy' },
        correlations: { attendancePct: 0.41 },
      },
      activeDiagnosticsTrainingManifestVersion: 'manifest-v1',
      activeDiagnosticsCalibrationVersion: 'isotonic-v1',
      activeDiagnosticsSplitSummary: { train: 1800, validation: 300, test: 300 },
      activeDiagnosticsWorldSplitSummary: { train: 4, validation: 1, test: 1 },
      activeDiagnosticsScenarioFamilies: { steady: 3, rescue: 2 },
      activeDiagnosticsHeadSupportSummary: { overallCourseRisk: { positives: 1200 } },
      activeDiagnosticsGovernedRunCount: 5,
      activeDiagnosticsSkippedRunCount: 0,
      activeDiagnosticsDisplayProbabilityAllowed: false,
      activeDiagnosticsSupportWarning: 'Held-out positive support is below the probability display threshold.',
      activeDiagnosticsPolicyDiagnostics: { gates: 'ok' },
      activeDiagnosticsCoEvidence: { mode: 'graph-aware' },
      activeDiagnosticsPolicyAcceptance: { policy: 'accepted' },
      activeDiagnosticsOverallCourseRuntime: { parity: 'aligned' },
      activeDiagnosticsQueueBurden: { mentor: 2 },
      activeDiagnosticsUiParity: { facultySurface: 'aligned' },
      selectedProofCheckpoint: selectedCheckpoint,
      selectedProofCheckpointDetail: checkpointDetail,
      selectedProofCheckpointBlocked: true,
      selectedProofCheckpointHasBlockedProgression: true,
      selectedProofCheckpointCanStepForward: false,
      selectedProofCheckpointCanPlayToEnd: false,
      proofPlaybackRestoreNotice: {
        tone: 'neutral',
        message: 'Proof playback restored to Semester 6 · Post TT1. Use Reset playback to clear the saved checkpoint.',
      },
      onCreateProofImport: () => {},
      onValidateLatestProofImport: () => {},
      onReviewPendingCrosswalks: () => {},
      onApproveLatestProofImport: () => {},
      onCreateProofRun: () => {},
      onRecomputeProofRunRisk: () => {},
      onActivateProofRun: () => {},
      onActivateProofSemester: () => {},
      onRetryProofRun: () => {},
      onArchiveProofRun: () => {},
      onRestoreProofSnapshot: () => {},
      onResetProofPlaybackSelection: () => {},
      onSelectProofCheckpoint: () => {},
      onStepProofPlayback: () => {},
      formatSplitSummary: summary => JSON.stringify(summary),
      formatKeyedCounts: summary => JSON.stringify(summary),
      formatHeadSupportSummary: summary => JSON.stringify(summary),
      formatDiagnosticSummary: summary => JSON.stringify(summary),
    }))

    expect(checkpointContainer.innerHTML).toContain('Playback progression is blocked until all queue items at this checkpoint are resolved.')
    expect(checkpointContainer.innerHTML).toContain('Queue items from the TT1 checkpoint are still unresolved.')
    expect(checkpointContainer.innerHTML).toContain('Proof playback restored')
    expect(checkpointContainer.innerHTML).toContain('Stage progression blocked')
  })

  it('renders a tabbed proof control plane with bounded operations scroll regions', () => {
    const selectedCheckpoint = buildCheckpoint({
      simulationStageCheckpointId: 'checkpoint_post_tt1',
      stageLabel: 'Post TT1',
      stageKey: 'post-tt1',
      semesterNumber: 6,
      playbackAccessible: true,
      stageAdvanceBlocked: false,
      blockedByCheckpointId: null,
      blockedProgressionReason: null,
    })

    const proofDashboard: ApiProofDashboard = {
      imports: [{
        curriculumImportVersionId: 'import_001',
        sourceLabel: 'MSRUAS workbook',
        sourceChecksum: 'source-sha',
        outputChecksum: 'output-sha',
        compilerVersion: 'compiler-v1',
        validationStatus: 'valid',
        unresolvedMappingCount: 0,
        status: 'approved',
        approvedAt: '2026-03-16T00:00:00.000Z',
        createdAt: '2026-03-16T00:00:00.000Z',
        certificate: {},
      }],
      latestValidation: null,
      crosswalkReviewQueue: [{
        officialCodeCrosswalkId: 'crosswalk_001',
        internalCompilerId: 'MC601',
        officialWebCode: 'CS601',
        confidence: 'high',
      }],
      proofRuns: [{
        simulationRunId: 'run_001',
        runLabel: 'Proof Run 1',
        status: 'active',
        activeFlag: true,
        seed: 42,
        createdAt: '2026-03-16T00:00:00.000Z',
        startedAt: '2026-03-16T00:00:00.000Z',
        completedAt: null,
        failureCode: null,
        failureMessage: null,
        progress: { phase: 'running', percent: 68 },
        metrics: {},
        queueAgeSeconds: 180,
        leaseState: 'leased',
        leaseExpiresAt: '2026-03-16T00:15:00.000Z',
        retryState: null,
        retryOfSimulationRunId: null,
        failureState: 'none',
      }],
      activeRunDetail: {
        simulationRunId: 'run_001',
        runLabel: 'Proof Run 1',
        seed: 42,
        activeOperationalSemester: 6,
        createdAt: '2026-03-16T00:00:00.000Z',
        startedAt: '2026-03-16T00:00:00.000Z',
        completedAt: null,
        status: 'active',
        failureCode: null,
        failureMessage: null,
        progress: { phase: 'running', percent: 68 },
        monitoringSummary: {
          riskAssessmentCount: 24,
          activeReassessmentCount: 5,
          alertDecisionCount: 6,
          acknowledgementCount: 2,
          resolutionCount: 1,
        },
        coverageDiagnostics: {
          behaviorProfileCoverage: { count: 120, expected: 120 },
          topicStateCoverage: { count: 640 },
          coStateCoverage: { count: 310 },
          questionTemplateCoverage: { count: 84 },
          questionResultCoverage: { count: 2400 },
          interventionResponseCoverage: { count: 36 },
          worldContextCoverage: { count: 12 },
        },
        modelDiagnostics: {
          featureRowCount: 2400,
          activeRunFeatureRowCount: 360,
          sourceRunCount: 5,
          runtimeSummary: {},
          overallCourseRuntimeSummary: {},
          queueBurdenSummary: {},
          stageRollups: [],
          acceptanceGateSummary: {},
          splitSummary: { train: 1800, validation: 300, test: 300 },
          worldSplitSummary: { train: 4, validation: 1, test: 1 },
          scenarioFamilySummary: { steady: 3, rescue: 2 },
          headSupportSummary: { overallCourseRisk: { positives: 1200 } },
          calibrationVersion: 'isotonic-v1',
          policyDiagnostics: { gates: 'ok' },
          coEvidenceDiagnostics: {
            totalRows: 360,
            fallbackCount: 40,
            byMode: {
              'offering-blueprint': 280,
              'rubric-derived': 40,
              'fallback-simulated': 40,
            },
          },
          uiParityDiagnostics: { facultySurface: 'aligned' },
          production: null,
          challenger: null,
          correlations: null,
        },
        queueDiagnostics: {
          queuedRunCount: 1,
          runningRunCount: 1,
          failedRunCount: 0,
          retryableRunCount: 0,
          retryInFlightCount: 0,
          oldestQueuedRunAgeSeconds: 180,
          expiredLeaseRunCount: 0,
        },
        workerDiagnostics: {
          queueAgeSeconds: 180,
          leaseState: 'leased',
          leaseExpiresAt: '2026-03-16T00:15:00.000Z',
          retryState: null,
          retryOfSimulationRunId: null,
          failureState: 'none',
          progressPhase: 'checkpoint-playback',
          progressPercent: 68,
        },
        checkpointReadiness: {
          totalCheckpointCount: 1,
          readyCheckpointCount: 1,
          blockedCheckpointCount: 0,
          playbackBlockedCheckpointCount: 0,
          totalBlockingQueueItemCount: 0,
          firstBlockedCheckpointId: null,
          lastReadyCheckpointId: 'checkpoint_post_tt1',
        },
        teacherAllocationLoad: [{
          teacherLoadProfileId: 'load_001',
          facultyName: 'Prof. Kavitha Rao',
          semesterNumber: 6,
          weeklyContactHours: 12,
          assignedCredits: 18,
        }],
        queuePreview: [{
          reassessmentEventId: 'queue_001',
          studentId: 'student_001',
          studentUsn: '1MS23CS001',
          studentName: 'Aarav Sharma',
          courseCode: 'CS601',
          assignedToRole: 'mentor',
          status: 'open',
          dueAt: '2026-03-17T00:00:00.000Z',
          sourceKind: 'checkpoint-playback',
          stageLabel: 'Post TT1',
          coEvidenceMode: 'fallback-simulated',
          riskChangeFromPreviousCheckpointScaled: 4,
          counterfactualLiftScaled: 7,
          title: 'Mentor follow-up',
          riskBand: 'High',
          riskProbScaled: 83,
          noActionRiskProbScaled: 89,
          taskType: 'follow-up',
          simulatedActionTaken: 'follow-up',
          recommendedAction: 'follow-up',
        }],
        snapshots: [{
          simulationResetSnapshotId: 'snapshot_001',
          snapshotLabel: 'Baseline snapshot',
          createdAt: '2026-03-16T00:00:00.000Z',
          payload: {},
        }],
        checkpoints: [selectedCheckpoint],
      },
      lifecycleAudit: [{
        simulationLifecycleAuditId: 'audit_001',
        actionType: 'proof-run-created',
        createdAt: '2026-03-16T00:00:00.000Z',
        createdByFacultyName: 'System',
      }],
      recentOperationalEvents: [{
        operationalTelemetryEventId: 'ops_evt_001',
        source: 'backend',
        name: 'startup.ready',
        level: 'info',
        timestamp: '2026-03-16T00:00:00.000Z',
        details: { host: '0.0.0.0' },
        createdAt: '2026-03-16T00:00:00.000Z',
      }],
    }

    render(createElement(SystemAdminProofDashboardWorkspace, {
      proofDashboard,
      proofDashboardLoading: false,
      initialActiveDashboardTab: 'summary',
      activeRunCheckpoints: [selectedCheckpoint],
      activeModelDiagnostics: { scenarioFamilySummary: { steady: 3, rescue: 2 } },
      activeProductionDiagnostics: null,
      activeDiagnosticsTrainingManifestVersion: 'manifest-v1',
      activeDiagnosticsCalibrationVersion: 'isotonic-v1',
      activeDiagnosticsSplitSummary: { train: 1800, validation: 300, test: 300 },
      activeDiagnosticsWorldSplitSummary: { train: 4, validation: 1, test: 1 },
      activeDiagnosticsScenarioFamilies: { steady: 3, rescue: 2 },
      activeDiagnosticsHeadSupportSummary: { overallCourseRisk: { positives: 1200 } },
      activeDiagnosticsGovernedRunCount: 5,
      activeDiagnosticsSkippedRunCount: 0,
      activeDiagnosticsDisplayProbabilityAllowed: false,
      activeDiagnosticsSupportWarning: 'Held-out positive support is below the probability display threshold.',
      activeDiagnosticsPolicyDiagnostics: { gates: 'ok' },
      activeDiagnosticsCoEvidence: {
        totalRows: 360,
        fallbackCount: 40,
        byMode: {
          'offering-blueprint': 280,
          'rubric-derived': 40,
          'fallback-simulated': 40,
        },
      },
      activeDiagnosticsPolicyAcceptance: { policy: 'accepted' },
      activeDiagnosticsOverallCourseRuntime: { parity: 'aligned' },
      activeDiagnosticsQueueBurden: { mentor: 2 },
      activeDiagnosticsUiParity: { facultySurface: 'aligned' },
      selectedProofCheckpoint: selectedCheckpoint,
      selectedProofCheckpointDetail: null,
      selectedProofCheckpointBlocked: false,
      selectedProofCheckpointHasBlockedProgression: false,
      selectedProofCheckpointCanStepForward: true,
      selectedProofCheckpointCanPlayToEnd: true,
      proofPlaybackRestoreNotice: null,
      onCreateProofImport: () => {},
      onValidateLatestProofImport: () => {},
      onReviewPendingCrosswalks: () => {},
      onApproveLatestProofImport: () => {},
      onCreateProofRun: () => {},
      onRecomputeProofRunRisk: () => {},
      onActivateProofRun: () => {},
      onActivateProofSemester: () => {},
      onRetryProofRun: () => {},
      onArchiveProofRun: () => {},
      onRestoreProofSnapshot: () => {},
      onResetProofPlaybackSelection: () => {},
      onSelectProofCheckpoint: () => {},
      onStepProofPlayback: () => {},
      formatSplitSummary: summary => JSON.stringify(summary),
      formatKeyedCounts: summary => JSON.stringify(summary),
      formatHeadSupportSummary: summary => JSON.stringify(summary),
      formatDiagnosticSummary: summary => JSON.stringify(summary),
    }))

    expect(screen.getByRole('tablist', { name: 'Proof control-plane sections' })).toBeTruthy()
    expect(screen.getByRole('tab', { name: 'Summary' })).toBeTruthy()
    expect(screen.getByRole('tab', { name: 'Checkpoint' })).toBeTruthy()
    expect(screen.getByRole('tab', { name: 'Operations' })).toBeTruthy()
    expect(screen.getByText('Action Pressure')).toBeTruthy()
    expect(screen.getByText('Queue Health')).toBeTruthy()
    expect(screen.getByText('Checkpoint Readiness')).toBeTruthy()
    expect(screen.getByText('Worker Lease')).toBeTruthy()

    fireEvent.click(screen.getByRole('tab', { name: 'Operations' }))

    const operationsRegion = document.querySelector('[data-proof-scroll-region="recent-operational-events"]') as HTMLElement | null
    expect(operationsRegion).toBeTruthy()
    expect(operationsRegion?.style.maxHeight).toBe('190px')
    expect(screen.getByRole('tabpanel').getAttribute('data-proof-section')).toBe('proof-dashboard-operations')

    cleanup()

    render(createElement(SystemAdminProofDashboardWorkspace, {
      proofDashboard,
      proofDashboardLoading: false,
      initialActiveDashboardTab: 'checkpoint',
      activeRunCheckpoints: [selectedCheckpoint],
      activeModelDiagnostics: { scenarioFamilySummary: { steady: 3, rescue: 2 } },
      activeProductionDiagnostics: null,
      activeDiagnosticsTrainingManifestVersion: 'manifest-v1',
      activeDiagnosticsCalibrationVersion: 'isotonic-v1',
      activeDiagnosticsSplitSummary: { train: 1800, validation: 300, test: 300 },
      activeDiagnosticsWorldSplitSummary: { train: 4, validation: 1, test: 1 },
      activeDiagnosticsScenarioFamilies: { steady: 3, rescue: 2 },
      activeDiagnosticsHeadSupportSummary: { overallCourseRisk: { positives: 1200 } },
      activeDiagnosticsGovernedRunCount: 5,
      activeDiagnosticsSkippedRunCount: 0,
      activeDiagnosticsDisplayProbabilityAllowed: false,
      activeDiagnosticsSupportWarning: 'Held-out positive support is below the probability display threshold.',
      activeDiagnosticsPolicyDiagnostics: { gates: 'ok' },
      activeDiagnosticsCoEvidence: {
        totalRows: 360,
        fallbackCount: 40,
        byMode: {
          'offering-blueprint': 280,
          'rubric-derived': 40,
          'fallback-simulated': 40,
        },
      },
      activeDiagnosticsPolicyAcceptance: { policy: 'accepted' },
      activeDiagnosticsOverallCourseRuntime: { parity: 'aligned' },
      activeDiagnosticsQueueBurden: { mentor: 2 },
      activeDiagnosticsUiParity: { facultySurface: 'aligned' },
      selectedProofCheckpoint: selectedCheckpoint,
      selectedProofCheckpointDetail: null,
      selectedProofCheckpointBlocked: false,
      selectedProofCheckpointHasBlockedProgression: false,
      selectedProofCheckpointCanStepForward: true,
      selectedProofCheckpointCanPlayToEnd: true,
      proofPlaybackRestoreNotice: null,
      onCreateProofImport: () => {},
      onValidateLatestProofImport: () => {},
      onReviewPendingCrosswalks: () => {},
      onApproveLatestProofImport: () => {},
      onCreateProofRun: () => {},
      onRecomputeProofRunRisk: () => {},
      onActivateProofRun: () => {},
      onActivateProofSemester: () => {},
      onRetryProofRun: () => {},
      onArchiveProofRun: () => {},
      onRestoreProofSnapshot: () => {},
      onResetProofPlaybackSelection: () => {},
      onSelectProofCheckpoint: () => {},
      onStepProofPlayback: () => {},
      formatSplitSummary: summary => JSON.stringify(summary),
      formatKeyedCounts: summary => JSON.stringify(summary),
      formatHeadSupportSummary: summary => JSON.stringify(summary),
      formatDiagnosticSummary: summary => JSON.stringify(summary),
    }))

    expect(screen.getByRole('tab', { name: 'Checkpoint' }).getAttribute('aria-selected')).toBe('true')
    expect(screen.getByText('Checkpoint Playback')).toBeTruthy()
    expect(document.querySelector('[data-proof-section="checkpoint-playback"]')).toBeTruthy()
  })

  it('renders a playback override banner when the pinned checkpoint semester differs from the activated operational semester', () => {
    const selectedCheckpoint = buildCheckpoint({
      simulationStageCheckpointId: 'checkpoint_post_tt2',
      semesterNumber: 5,
      stageLabel: 'Post TT2',
      blockedProgressionReason: null,
      playbackAccessible: true,
      stageAdvanceBlocked: false,
      blockedByCheckpointId: null,
    })
    const checkpoints = [
      buildCheckpoint({
        simulationStageCheckpointId: 'checkpoint_sem4',
        semesterNumber: 4,
        stageLabel: 'Semester 4',
        stageKey: 'post-assignments',
        stageOrder: 1,
        previousCheckpointId: null,
        nextCheckpointId: 'checkpoint_sem5',
        playbackAccessible: true,
        stageAdvanceBlocked: false,
        blockedByCheckpointId: null,
        blockedProgressionReason: null,
      }),
      buildCheckpoint({
        simulationStageCheckpointId: 'checkpoint_sem5',
        semesterNumber: 5,
        stageLabel: 'Semester 5',
        stageKey: 'post-tt2',
        stageOrder: 1,
        previousCheckpointId: 'checkpoint_sem4',
        nextCheckpointId: 'checkpoint_sem6',
        playbackAccessible: true,
        stageAdvanceBlocked: false,
        blockedByCheckpointId: null,
        blockedProgressionReason: null,
      }),
      buildCheckpoint({
        simulationStageCheckpointId: 'checkpoint_sem6',
        semesterNumber: 6,
        stageLabel: 'Semester 6',
        stageKey: 'post-see',
        stageOrder: 2,
        previousCheckpointId: 'checkpoint_sem5',
        nextCheckpointId: null,
        playbackAccessible: true,
        stageAdvanceBlocked: false,
        blockedByCheckpointId: null,
        blockedProgressionReason: null,
      }),
    ]

    const proofDashboard: ApiProofDashboard = {
      imports: [],
      latestValidation: null,
      crosswalkReviewQueue: [],
      proofRuns: [],
      activeRunDetail: {
        simulationRunId: 'run_001',
        runLabel: 'Proof Run 1',
        seed: 42,
        activeOperationalSemester: 6,
        createdAt: '2026-03-16T00:00:00.000Z',
        startedAt: '2026-03-16T00:00:00.000Z',
        completedAt: null,
        status: 'active',
        failureCode: null,
        failureMessage: null,
        progress: null,
        monitoringSummary: {
          riskAssessmentCount: 0,
          activeReassessmentCount: 0,
          alertDecisionCount: 0,
          acknowledgementCount: 0,
          resolutionCount: 0,
        },
        coverageDiagnostics: {
          behaviorProfileCoverage: { count: 1, expected: 1 },
          topicStateCoverage: { count: 1 },
          coStateCoverage: { count: 1 },
          questionTemplateCoverage: { count: 1 },
          questionResultCoverage: { count: 1 },
          interventionResponseCoverage: { count: 1 },
          worldContextCoverage: { count: 1 },
        },
        modelDiagnostics: {
          featureRowCount: 1,
          activeRunFeatureRowCount: 1,
          sourceRunCount: 1,
          production: null,
          challenger: null,
          correlations: null,
        },
        queueDiagnostics: {
          queuedRunCount: 0,
          runningRunCount: 0,
          failedRunCount: 0,
          retryableRunCount: 0,
          retryInFlightCount: 0,
          oldestQueuedRunAgeSeconds: 0,
          expiredLeaseRunCount: 0,
        },
        workerDiagnostics: null,
        checkpointReadiness: null,
        teacherAllocationLoad: [],
        queuePreview: [],
        snapshots: [],
        checkpoints,
      },
      lifecycleAudit: [],
      recentOperationalEvents: [],
    }

    const markup = renderToStaticMarkup(createElement(SystemAdminProofDashboardWorkspace, {
      proofDashboard,
      proofDashboardLoading: false,
      activeRunCheckpoints: checkpoints,
      activeModelDiagnostics: null,
      activeProductionDiagnostics: null,
      activeDiagnosticsTrainingManifestVersion: null,
      activeDiagnosticsCalibrationVersion: null,
      activeDiagnosticsSplitSummary: null,
      activeDiagnosticsWorldSplitSummary: null,
      activeDiagnosticsScenarioFamilies: null,
      activeDiagnosticsHeadSupportSummary: null,
      activeDiagnosticsGovernedRunCount: null,
      activeDiagnosticsSkippedRunCount: null,
      activeDiagnosticsDisplayProbabilityAllowed: null,
      activeDiagnosticsSupportWarning: null,
      activeDiagnosticsPolicyDiagnostics: null,
      activeDiagnosticsCoEvidence: null,
      activeDiagnosticsPolicyAcceptance: null,
      activeDiagnosticsOverallCourseRuntime: null,
      activeDiagnosticsQueueBurden: null,
      activeDiagnosticsUiParity: null,
      selectedProofCheckpoint: selectedCheckpoint,
      selectedProofCheckpointDetail: null,
      selectedProofCheckpointBlocked: false,
      selectedProofCheckpointHasBlockedProgression: false,
      selectedProofCheckpointCanStepForward: true,
      selectedProofCheckpointCanPlayToEnd: true,
      proofPlaybackRestoreNotice: null,
      onCreateProofImport: () => {},
      onValidateLatestProofImport: () => {},
      onReviewPendingCrosswalks: () => {},
      onApproveLatestProofImport: () => {},
      onCreateProofRun: () => {},
      onRecomputeProofRunRisk: () => {},
      onActivateProofRun: () => {},
      onActivateProofSemester: () => {},
      onRetryProofRun: () => {},
      onArchiveProofRun: () => {},
      onRestoreProofSnapshot: () => {},
      onResetProofPlaybackSelection: () => {},
      onSelectProofCheckpoint: () => {},
      onStepProofPlayback: () => {},
      formatSplitSummary: summary => JSON.stringify(summary),
      formatKeyedCounts: summary => JSON.stringify(summary),
      formatHeadSupportSummary: summary => JSON.stringify(summary),
      formatDiagnosticSummary: summary => JSON.stringify(summary),
    }))

    expect(markup).toContain('data-proof-action="proof-activate-semester-5"')
    expect(markup).toContain('data-proof-action="proof-activate-semester-6"')
    expect(markup).toContain('Operational semester')
    expect(markup).toContain('Semester 6')
    expect(markup).toContain('Playback override active.')
    expect(markup).toContain('pinned to Semester 5')
    expect(markup).toContain('operational semester remains Semester 6')
    expect(markup).toContain('data-proof-shell="shared"')
    expect(markup).toContain('data-proof-launcher="floating"')
  })

  it('renders a persistent proof workflow rail with collapsed scope details', () => {
    const selectedCheckpoint = buildCheckpoint({
      simulationStageCheckpointId: 'checkpoint_sem6_post_see',
      semesterNumber: 6,
      stageLabel: 'Post SEE',
      stageKey: 'post-see',
      stageAdvanceBlocked: false,
      blockedByCheckpointId: null,
      blockedProgressionReason: null,
      playbackAccessible: true,
    })

    const proofDashboard: ApiProofDashboard = {
      imports: [],
      latestValidation: null,
      crosswalkReviewQueue: [],
      proofRuns: [],
      activeRunDetail: {
        simulationRunId: 'run_rail',
        runLabel: 'Proof Run Rail',
        seed: 11,
        activeOperationalSemester: 6,
        createdAt: '2026-04-02T00:00:00.000Z',
        startedAt: '2026-04-02T00:00:00.000Z',
        completedAt: null,
        status: 'active',
        failureCode: null,
        failureMessage: null,
        progress: null,
        monitoringSummary: {
          riskAssessmentCount: 12,
          activeReassessmentCount: 2,
          alertDecisionCount: 3,
          acknowledgementCount: 1,
          resolutionCount: 0,
        },
        coverageDiagnostics: {
          behaviorProfileCoverage: { count: 120, expected: 120 },
          topicStateCoverage: { count: 12 },
          coStateCoverage: { count: 12 },
          questionTemplateCoverage: { count: 12 },
          questionResultCoverage: { count: 120 },
          interventionResponseCoverage: { count: 3 },
          worldContextCoverage: { count: 6 },
        },
        modelDiagnostics: {
          featureRowCount: 120,
          activeRunFeatureRowCount: 24,
          sourceRunCount: 3,
          production: null,
          challenger: null,
          correlations: null,
        },
        queueDiagnostics: {
          queuedRunCount: 1,
          runningRunCount: 0,
          failedRunCount: 0,
          retryableRunCount: 0,
          retryInFlightCount: 0,
          oldestQueuedRunAgeSeconds: 120,
          expiredLeaseRunCount: 0,
        },
        workerDiagnostics: null,
        checkpointReadiness: {
          totalCheckpointCount: 1,
          readyCheckpointCount: 1,
          blockedCheckpointCount: 0,
          playbackBlockedCheckpointCount: 0,
          totalBlockingQueueItemCount: 0,
          firstBlockedCheckpointId: null,
          lastReadyCheckpointId: selectedCheckpoint.simulationStageCheckpointId,
        },
        teacherAllocationLoad: [],
        queuePreview: [],
        snapshots: [],
        checkpoints: [selectedCheckpoint],
      },
      lifecycleAudit: [],
      recentOperationalEvents: [],
    }

    const markup = renderToStaticMarkup(createElement(SystemAdminProofDashboardWorkspace, {
      proofDashboard,
      proofDashboardLoading: false,
      activeRunCheckpoints: [selectedCheckpoint],
      activeModelDiagnostics: null,
      activeProductionDiagnostics: null,
      activeDiagnosticsTrainingManifestVersion: null,
      activeDiagnosticsCalibrationVersion: null,
      activeDiagnosticsSplitSummary: null,
      activeDiagnosticsWorldSplitSummary: null,
      activeDiagnosticsScenarioFamilies: null,
      activeDiagnosticsHeadSupportSummary: null,
      activeDiagnosticsGovernedRunCount: null,
      activeDiagnosticsSkippedRunCount: null,
      activeDiagnosticsDisplayProbabilityAllowed: null,
      activeDiagnosticsSupportWarning: null,
      activeDiagnosticsPolicyDiagnostics: null,
      activeDiagnosticsCoEvidence: null,
      activeDiagnosticsPolicyAcceptance: null,
      activeDiagnosticsOverallCourseRuntime: null,
      activeDiagnosticsQueueBurden: null,
      activeDiagnosticsUiParity: null,
      selectedProofCheckpoint: selectedCheckpoint,
      selectedProofCheckpointDetail: null,
      selectedProofCheckpointBlocked: false,
      selectedProofCheckpointHasBlockedProgression: false,
      selectedProofCheckpointCanStepForward: false,
      selectedProofCheckpointCanPlayToEnd: false,
      proofPlaybackRestoreNotice: null,
      onCreateProofImport: () => {},
      onValidateLatestProofImport: () => {},
      onReviewPendingCrosswalks: () => {},
      onApproveLatestProofImport: () => {},
      onCreateProofRun: () => {},
      onRecomputeProofRunRisk: () => {},
      onActivateProofRun: () => {},
      onActivateProofSemester: () => {},
      onRetryProofRun: () => {},
      onArchiveProofRun: () => {},
      onRestoreProofSnapshot: () => {},
      onResetProofPlaybackSelection: () => {},
      onSelectProofCheckpoint: () => {},
      onStepProofPlayback: () => {},
      formatSplitSummary: summary => JSON.stringify(summary),
      formatKeyedCounts: summary => JSON.stringify(summary),
      formatHeadSupportSummary: summary => JSON.stringify(summary),
      formatDiagnosticSummary: summary => JSON.stringify(summary),
    }))

    expect(markup).toContain('data-proof-section="proof-dashboard-rail"')
    expect(markup).toContain('Semester + checkpoint controls stay visible here.')
    expect(markup).toContain(`color:${getAccessiblePrimaryAccent()}`)
    expect(markup).toContain('data-proof-section="proof-dashboard-scope-details"')
    expect(markup).toContain('<summary')
    expect(markup).toContain('Scope details')
  })

  it('marks proof scroll regions focusable for keyboard scrolling', () => {
    const selectedCheckpoint = buildCheckpoint({
      simulationStageCheckpointId: 'checkpoint_focusable_scroll_region',
      semesterNumber: 6,
      stageLabel: 'Post SEE',
      stageKey: 'post-see',
      stageAdvanceBlocked: false,
      blockedByCheckpointId: null,
      blockedProgressionReason: null,
      playbackAccessible: true,
    })

    const proofDashboard: ApiProofDashboard = {
      imports: [],
      latestValidation: null,
      crosswalkReviewQueue: [],
      proofRuns: [],
      activeRunDetail: {
        simulationRunId: 'run_focusable_scroll_region',
        runLabel: 'Focusable Scroll Region Run',
        seed: 13,
        activeOperationalSemester: 6,
        createdAt: '2026-04-02T00:00:00.000Z',
        startedAt: '2026-04-02T00:00:00.000Z',
        completedAt: null,
        status: 'active',
        failureCode: null,
        failureMessage: null,
        progress: null,
        monitoringSummary: {
          riskAssessmentCount: 0,
          activeReassessmentCount: 0,
          alertDecisionCount: 0,
          acknowledgementCount: 0,
          resolutionCount: 0,
        },
        coverageDiagnostics: {
          behaviorProfileCoverage: { count: 120, expected: 120 },
          topicStateCoverage: { count: 0 },
          coStateCoverage: { count: 0 },
          questionTemplateCoverage: { count: 0 },
          questionResultCoverage: { count: 0 },
          interventionResponseCoverage: { count: 0 },
          worldContextCoverage: { count: 0 },
        },
        modelDiagnostics: {
          featureRowCount: 120,
          activeRunFeatureRowCount: 0,
          sourceRunCount: 1,
          production: null,
          challenger: null,
          correlations: null,
        },
        queueDiagnostics: {
          queuedRunCount: 0,
          runningRunCount: 0,
          failedRunCount: 0,
          retryableRunCount: 0,
          retryInFlightCount: 0,
          oldestQueuedRunAgeSeconds: null,
          expiredLeaseRunCount: 0,
        },
        workerDiagnostics: null,
        checkpointReadiness: {
          totalCheckpointCount: 1,
          readyCheckpointCount: 1,
          blockedCheckpointCount: 0,
          playbackBlockedCheckpointCount: 0,
          totalBlockingQueueItemCount: 0,
          firstBlockedCheckpointId: null,
          lastReadyCheckpointId: selectedCheckpoint.simulationStageCheckpointId,
        },
        teacherAllocationLoad: [],
        queuePreview: [],
        snapshots: [],
        checkpoints: [selectedCheckpoint],
      },
      lifecycleAudit: [],
      recentOperationalEvents: [],
    }

    render(createElement(SystemAdminProofDashboardWorkspace, {
      proofDashboard,
      proofDashboardLoading: false,
      initialActiveDashboardTab: 'operations',
      activeRunCheckpoints: [selectedCheckpoint],
      activeModelDiagnostics: null,
      activeProductionDiagnostics: null,
      activeDiagnosticsTrainingManifestVersion: null,
      activeDiagnosticsCalibrationVersion: null,
      activeDiagnosticsSplitSummary: null,
      activeDiagnosticsWorldSplitSummary: null,
      activeDiagnosticsScenarioFamilies: null,
      activeDiagnosticsHeadSupportSummary: null,
      activeDiagnosticsGovernedRunCount: null,
      activeDiagnosticsSkippedRunCount: null,
      activeDiagnosticsDisplayProbabilityAllowed: null,
      activeDiagnosticsSupportWarning: null,
      activeDiagnosticsPolicyDiagnostics: null,
      activeDiagnosticsCoEvidence: null,
      activeDiagnosticsPolicyAcceptance: null,
      activeDiagnosticsOverallCourseRuntime: null,
      activeDiagnosticsQueueBurden: null,
      activeDiagnosticsUiParity: null,
      selectedProofCheckpoint: selectedCheckpoint,
      selectedProofCheckpointDetail: null,
      selectedProofCheckpointBlocked: false,
      selectedProofCheckpointHasBlockedProgression: false,
      selectedProofCheckpointCanStepForward: false,
      selectedProofCheckpointCanPlayToEnd: false,
      proofPlaybackRestoreNotice: null,
      onCreateProofImport: () => {},
      onValidateLatestProofImport: () => {},
      onReviewPendingCrosswalks: () => {},
      onApproveLatestProofImport: () => {},
      onCreateProofRun: () => {},
      onRecomputeProofRunRisk: () => {},
      onActivateProofRun: () => {},
      onActivateProofSemester: () => {},
      onRetryProofRun: () => {},
      onArchiveProofRun: () => {},
      onRestoreProofSnapshot: () => {},
      onResetProofPlaybackSelection: () => {},
      onSelectProofCheckpoint: () => {},
      onStepProofPlayback: () => {},
      formatSplitSummary: summary => JSON.stringify(summary),
      formatKeyedCounts: summary => JSON.stringify(summary),
      formatHeadSupportSummary: summary => JSON.stringify(summary),
      formatDiagnosticSummary: summary => JSON.stringify(summary),
    }))

    const scrollRegions = Array.from(document.querySelectorAll<HTMLElement>('[data-proof-scroll-region]'))
    expect(scrollRegions.length).toBeGreaterThan(0)
    scrollRegions.forEach(region => {
      expect(region.tabIndex).toBe(0)
      const labelledBy = region.getAttribute('aria-labelledby')
      expect(labelledBy).toBeTruthy()
      expect(document.getElementById(labelledBy ?? '')).not.toBeNull()
    })

    const administrativeActionsRegion = document.querySelector<HTMLElement>('[data-proof-scroll-region="administrative-actions"]')
    expect(administrativeActionsRegion).not.toBeNull()
    expect(document.getElementById(administrativeActionsRegion?.getAttribute('aria-labelledby') ?? '')?.textContent).toBe('Administrative Actions')
  })

  it('toggles checkpoint evidence between queue and offering detail without stacking both panes', () => {
    const selectedCheckpoint = buildCheckpoint({
      simulationStageCheckpointId: 'checkpoint_toggle',
      semesterNumber: 6,
      stageLabel: 'Post SEE',
      stageKey: 'post-see',
      stageAdvanceBlocked: false,
      blockedByCheckpointId: null,
      blockedProgressionReason: null,
      playbackAccessible: true,
    })
    const checkpointDetail: ApiProofRunCheckpointDetail = {
      checkpoint: selectedCheckpoint,
      queuePreview: [{
        simulationStageQueueProjectionId: 'queue_001',
        simulationStageCheckpointId: selectedCheckpoint.simulationStageCheckpointId,
        courseCode: 'CS6104',
        assignedToRole: 'mentor',
        taskType: 'targeted-tutoring',
        status: 'watch',
        riskBand: 'Medium',
        riskProbScaled: 68,
        noActionRiskProbScaled: 83,
        simulatedActionTaken: 'call-guardian',
        recommendedAction: 'call-guardian',
        coEvidenceMode: 'fallback-simulated',
        riskChangeFromPreviousCheckpointScaled: -4,
        counterfactualLiftScaled: 9,
      }],
      offeringRollups: [{
        simulationStageOfferingProjectionId: 'offering_001',
        simulationStageCheckpointId: selectedCheckpoint.simulationStageCheckpointId,
        courseCode: 'CS6104',
        sectionCode: 'A',
        pendingAction: 'targeted tutoring',
        projection: {
          averageRiskProbScaled: 64,
          openQueueCount: 3,
          coEvidenceMode: 'rubric-derived',
          riskChangeFromPreviousCheckpointScaled: -2,
          counterfactualLiftScaled: 6,
        },
      }],
    }

    const proofDashboard: ApiProofDashboard = {
      imports: [],
      latestValidation: null,
      crosswalkReviewQueue: [],
      proofRuns: [],
      activeRunDetail: {
        simulationRunId: 'run_toggle',
        runLabel: 'Toggle Detail Run',
        seed: 7,
        activeOperationalSemester: 6,
        createdAt: '2026-04-02T00:00:00.000Z',
        startedAt: '2026-04-02T00:00:00.000Z',
        completedAt: null,
        status: 'active',
        failureCode: null,
        failureMessage: null,
        progress: null,
        monitoringSummary: {
          riskAssessmentCount: 1,
          activeReassessmentCount: 1,
          alertDecisionCount: 1,
          acknowledgementCount: 0,
          resolutionCount: 0,
        },
        coverageDiagnostics: {
          behaviorProfileCoverage: { count: 1, expected: 1 },
          topicStateCoverage: { count: 1 },
          coStateCoverage: { count: 1 },
          questionTemplateCoverage: { count: 1 },
          questionResultCoverage: { count: 1 },
          interventionResponseCoverage: { count: 1 },
          worldContextCoverage: { count: 1 },
        },
        modelDiagnostics: {
          featureRowCount: 1,
          activeRunFeatureRowCount: 1,
          sourceRunCount: 1,
          production: null,
          challenger: null,
          correlations: null,
        },
        queueDiagnostics: {
          queuedRunCount: 0,
          runningRunCount: 0,
          failedRunCount: 0,
          retryableRunCount: 0,
          retryInFlightCount: 0,
          oldestQueuedRunAgeSeconds: 0,
          expiredLeaseRunCount: 0,
        },
        workerDiagnostics: null,
        checkpointReadiness: null,
        teacherAllocationLoad: [],
        queuePreview: [],
        snapshots: [],
        checkpoints: [selectedCheckpoint],
      },
      lifecycleAudit: [],
      recentOperationalEvents: [],
    }

    render(createElement(SystemAdminProofDashboardWorkspace, {
      proofDashboard,
      proofDashboardLoading: false,
      initialActiveDashboardTab: 'checkpoint',
      activeRunCheckpoints: [selectedCheckpoint],
      activeModelDiagnostics: null,
      activeProductionDiagnostics: null,
      activeDiagnosticsTrainingManifestVersion: null,
      activeDiagnosticsCalibrationVersion: null,
      activeDiagnosticsSplitSummary: null,
      activeDiagnosticsWorldSplitSummary: null,
      activeDiagnosticsScenarioFamilies: null,
      activeDiagnosticsHeadSupportSummary: null,
      activeDiagnosticsGovernedRunCount: null,
      activeDiagnosticsSkippedRunCount: null,
      activeDiagnosticsDisplayProbabilityAllowed: null,
      activeDiagnosticsSupportWarning: null,
      activeDiagnosticsPolicyDiagnostics: null,
      activeDiagnosticsCoEvidence: null,
      activeDiagnosticsPolicyAcceptance: null,
      activeDiagnosticsOverallCourseRuntime: null,
      activeDiagnosticsQueueBurden: null,
      activeDiagnosticsUiParity: null,
      selectedProofCheckpoint: selectedCheckpoint,
      selectedProofCheckpointDetail: checkpointDetail,
      selectedProofCheckpointBlocked: false,
      selectedProofCheckpointHasBlockedProgression: false,
      selectedProofCheckpointCanStepForward: false,
      selectedProofCheckpointCanPlayToEnd: false,
      proofPlaybackRestoreNotice: null,
      onCreateProofImport: () => {},
      onValidateLatestProofImport: () => {},
      onReviewPendingCrosswalks: () => {},
      onApproveLatestProofImport: () => {},
      onCreateProofRun: () => {},
      onRecomputeProofRunRisk: () => {},
      onActivateProofRun: () => {},
      onActivateProofSemester: () => {},
      onRetryProofRun: () => {},
      onArchiveProofRun: () => {},
      onRestoreProofSnapshot: () => {},
      onResetProofPlaybackSelection: () => {},
      onSelectProofCheckpoint: () => {},
      onStepProofPlayback: () => {},
      formatSplitSummary: summary => JSON.stringify(summary),
      formatKeyedCounts: summary => JSON.stringify(summary),
      formatHeadSupportSummary: summary => JSON.stringify(summary),
      formatDiagnosticSummary: summary => JSON.stringify(summary),
    }))

    expect(screen.getByText('Stage queue preview')).toBeTruthy()
    expect(screen.queryByText('Offering action summary')).toBeNull()

    fireEvent.click(screen.getByRole('button', { name: 'Offering Detail' }))

    expect(screen.getByText('Offering action summary')).toBeTruthy()
    expect(screen.queryByText('Stage queue preview')).toBeNull()
  })

  it('renders explicit early-semester activation controls for semesters 1 through 3', () => {
    const selectedCheckpoint = buildCheckpoint({
      simulationStageCheckpointId: 'checkpoint_sem1',
      semesterNumber: 1,
      stageKey: 'semester-1',
      stageLabel: 'Semester 1',
      stageDescription: 'Introductory semester checkpoint.',
      stageOrder: 1,
      previousCheckpointId: null,
      nextCheckpointId: 'checkpoint_sem2',
      playbackAccessible: true,
      stageAdvanceBlocked: false,
      blockedByCheckpointId: null,
      blockedProgressionReason: null,
      highRiskCount: 2,
      mediumRiskCount: 4,
      lowRiskCount: 18,
      openQueueCount: 1,
      watchQueueCount: 1,
      resolvedQueueCount: 0,
      watchStudentCount: 1,
      blockingQueueItemCount: 1,
    })
    const checkpoints = [
      selectedCheckpoint,
      buildCheckpoint({
        simulationStageCheckpointId: 'checkpoint_sem2',
        semesterNumber: 2,
        stageKey: 'semester-2',
        stageLabel: 'Semester 2',
        stageDescription: 'Intermediate semester checkpoint.',
        stageOrder: 2,
        previousCheckpointId: 'checkpoint_sem1',
        nextCheckpointId: 'checkpoint_sem3',
        playbackAccessible: true,
        stageAdvanceBlocked: false,
        blockedByCheckpointId: null,
        blockedProgressionReason: null,
        highRiskCount: 3,
        mediumRiskCount: 5,
        lowRiskCount: 16,
        openQueueCount: 1,
        watchQueueCount: 1,
        resolvedQueueCount: 1,
        watchStudentCount: 1,
        blockingQueueItemCount: 0,
      }),
      buildCheckpoint({
        simulationStageCheckpointId: 'checkpoint_sem3',
        semesterNumber: 3,
        stageKey: 'semester-3',
        stageLabel: 'Semester 3',
        stageDescription: 'Early-semester checkpoint used to verify activation determinism.',
        stageOrder: 3,
        previousCheckpointId: 'checkpoint_sem2',
        nextCheckpointId: null,
        playbackAccessible: true,
        stageAdvanceBlocked: false,
        blockedByCheckpointId: null,
        blockedProgressionReason: null,
        highRiskCount: 4,
        mediumRiskCount: 6,
        lowRiskCount: 14,
        openQueueCount: 2,
        watchQueueCount: 1,
        resolvedQueueCount: 1,
        watchStudentCount: 2,
        blockingQueueItemCount: 0,
      }),
    ]

    const proofDashboard: ApiProofDashboard = {
      imports: [],
      latestValidation: null,
      crosswalkReviewQueue: [],
      proofRuns: [],
      activeRunDetail: {
        simulationRunId: 'run_001',
        runLabel: 'Proof Run 1',
        seed: 42,
        activeOperationalSemester: 3,
        createdAt: '2026-03-16T00:00:00.000Z',
        startedAt: '2026-03-16T00:00:00.000Z',
        completedAt: null,
        status: 'active',
        failureCode: null,
        failureMessage: null,
        progress: null,
        monitoringSummary: {
          riskAssessmentCount: 0,
          activeReassessmentCount: 0,
          alertDecisionCount: 0,
          acknowledgementCount: 0,
          resolutionCount: 0,
        },
        coverageDiagnostics: {
          behaviorProfileCoverage: { count: 1, expected: 1 },
          topicStateCoverage: { count: 1 },
          coStateCoverage: { count: 1 },
          questionTemplateCoverage: { count: 1 },
          questionResultCoverage: { count: 1 },
          interventionResponseCoverage: { count: 1 },
          worldContextCoverage: { count: 1 },
        },
        modelDiagnostics: {
          featureRowCount: 1,
          activeRunFeatureRowCount: 1,
          sourceRunCount: 1,
          production: null,
          challenger: null,
          correlations: null,
        },
        queueDiagnostics: {
          queuedRunCount: 0,
          runningRunCount: 0,
          failedRunCount: 0,
          retryableRunCount: 0,
          retryInFlightCount: 0,
          oldestQueuedRunAgeSeconds: 0,
          expiredLeaseRunCount: 0,
        },
        workerDiagnostics: null,
        checkpointReadiness: null,
        teacherAllocationLoad: [],
        queuePreview: [],
        snapshots: [],
        checkpoints,
      },
      lifecycleAudit: [],
      recentOperationalEvents: [],
    }

    const markup = renderToStaticMarkup(createElement(SystemAdminProofDashboardWorkspace, {
      proofDashboard,
      proofDashboardLoading: false,
      activeRunCheckpoints: checkpoints,
      activeModelDiagnostics: null,
      activeProductionDiagnostics: null,
      activeDiagnosticsTrainingManifestVersion: null,
      activeDiagnosticsCalibrationVersion: null,
      activeDiagnosticsSplitSummary: null,
      activeDiagnosticsWorldSplitSummary: null,
      activeDiagnosticsScenarioFamilies: null,
      activeDiagnosticsHeadSupportSummary: null,
      activeDiagnosticsGovernedRunCount: null,
      activeDiagnosticsSkippedRunCount: null,
      activeDiagnosticsDisplayProbabilityAllowed: null,
      activeDiagnosticsSupportWarning: null,
      activeDiagnosticsPolicyDiagnostics: null,
      activeDiagnosticsCoEvidence: null,
      activeDiagnosticsPolicyAcceptance: null,
      activeDiagnosticsOverallCourseRuntime: null,
      activeDiagnosticsQueueBurden: null,
      activeDiagnosticsUiParity: null,
      selectedProofCheckpoint: selectedCheckpoint,
      selectedProofCheckpointDetail: null,
      selectedProofCheckpointBlocked: false,
      selectedProofCheckpointHasBlockedProgression: false,
      selectedProofCheckpointCanStepForward: true,
      selectedProofCheckpointCanPlayToEnd: true,
      proofPlaybackRestoreNotice: {
        tone: 'neutral',
        message: 'Proof playback restored to Semester 1 · Semester 1. Use Reset playback to clear the saved checkpoint.',
      },
      onCreateProofImport: () => {},
      onValidateLatestProofImport: () => {},
      onReviewPendingCrosswalks: () => {},
      onApproveLatestProofImport: () => {},
      onCreateProofRun: () => {},
      onRecomputeProofRunRisk: () => {},
      onActivateProofRun: () => {},
      onActivateProofSemester: () => {},
      onRetryProofRun: () => {},
      onArchiveProofRun: () => {},
      onRestoreProofSnapshot: () => {},
      onResetProofPlaybackSelection: () => {},
      onSelectProofCheckpoint: () => {},
      onStepProofPlayback: () => {},
      formatSplitSummary: summary => JSON.stringify(summary),
      formatKeyedCounts: summary => JSON.stringify(summary),
      formatHeadSupportSummary: summary => JSON.stringify(summary),
      formatDiagnosticSummary: summary => JSON.stringify(summary),
    }))

    expect(markup).toContain('data-proof-action="proof-activate-semester-1"')
    expect(markup).toContain('data-proof-action="proof-activate-semester-2"')
    expect(markup).toContain('data-proof-action="proof-activate-semester-3"')
    expect(markup).toContain('Sem 1')
    expect(markup).toContain('Sem 2')
    expect(markup).toContain('Sem 3')
    expect(markup).toContain('Playback override active.')
    expect(markup).toContain('pinned to Semester 1')
    expect(markup).toContain('operational semester remains Semester 3')
  })

  it('keeps the checkpoint tab selected while checkpoint playback is still reloading', async () => {
    const selectedCheckpoint = buildCheckpoint({
      simulationStageCheckpointId: 'checkpoint_sem1_pre_tt1',
      semesterNumber: 1,
      stageKey: 'pre-tt1',
      stageLabel: 'Pre TT1',
      stageDescription: 'Checkpoint restore should stay pinned while the playback state hydrates.',
      stageOrder: 1,
      previousCheckpointId: null,
      nextCheckpointId: null,
      playbackAccessible: true,
      stageAdvanceBlocked: false,
      blockedByCheckpointId: null,
      blockedProgressionReason: null,
      highRiskCount: 0,
      mediumRiskCount: 0,
      lowRiskCount: 24,
      openQueueCount: 0,
      watchQueueCount: 0,
      resolvedQueueCount: 0,
      watchStudentCount: 0,
      blockingQueueItemCount: 0,
    })

    const proofDashboard: ApiProofDashboard = {
      imports: [],
      latestValidation: null,
      crosswalkReviewQueue: [],
      proofRuns: [],
      activeRunDetail: {
        simulationRunId: 'run_checkpoint_restore',
        runLabel: 'Checkpoint Restore Run',
        seed: 101,
        activeOperationalSemester: 1,
        createdAt: '2026-04-02T00:00:00.000Z',
        startedAt: '2026-04-02T00:00:00.000Z',
        completedAt: null,
        status: 'active',
        failureCode: null,
        failureMessage: null,
        progress: null,
        monitoringSummary: {
          riskAssessmentCount: 0,
          activeReassessmentCount: 0,
          alertDecisionCount: 0,
          acknowledgementCount: 0,
          resolutionCount: 0,
        },
        coverageDiagnostics: {
          behaviorProfileCoverage: { count: 1, expected: 1 },
          topicStateCoverage: { count: 1 },
          coStateCoverage: { count: 1 },
          questionTemplateCoverage: { count: 1 },
          questionResultCoverage: { count: 1 },
          interventionResponseCoverage: { count: 1 },
          worldContextCoverage: { count: 1 },
        },
        modelDiagnostics: {
          featureRowCount: 1,
          activeRunFeatureRowCount: 1,
          sourceRunCount: 1,
          production: null,
          challenger: null,
          correlations: null,
        },
        queueDiagnostics: {
          queuedRunCount: 0,
          runningRunCount: 0,
          failedRunCount: 0,
          retryableRunCount: 0,
          retryInFlightCount: 0,
          oldestQueuedRunAgeSeconds: 0,
          expiredLeaseRunCount: 0,
        },
        workerDiagnostics: null,
        checkpointReadiness: null,
        teacherAllocationLoad: [],
        queuePreview: [],
        snapshots: [],
        checkpoints: [selectedCheckpoint],
      },
      lifecycleAudit: [],
      recentOperationalEvents: [],
    }

    const baseProps = {
      proofDashboard,
      activeModelDiagnostics: null,
      activeProductionDiagnostics: null,
      activeDiagnosticsTrainingManifestVersion: null,
      activeDiagnosticsCalibrationVersion: null,
      activeDiagnosticsSplitSummary: null,
      activeDiagnosticsWorldSplitSummary: null,
      activeDiagnosticsScenarioFamilies: null,
      activeDiagnosticsHeadSupportSummary: null,
      activeDiagnosticsGovernedRunCount: null,
      activeDiagnosticsSkippedRunCount: null,
      activeDiagnosticsDisplayProbabilityAllowed: null,
      activeDiagnosticsSupportWarning: null,
      activeDiagnosticsPolicyDiagnostics: null,
      activeDiagnosticsCoEvidence: null,
      activeDiagnosticsPolicyAcceptance: null,
      activeDiagnosticsOverallCourseRuntime: null,
      activeDiagnosticsQueueBurden: null,
      activeDiagnosticsUiParity: null,
      selectedProofCheckpointDetail: null,
      selectedProofCheckpointBlocked: false,
      selectedProofCheckpointHasBlockedProgression: false,
      selectedProofCheckpointCanStepForward: true,
      selectedProofCheckpointCanPlayToEnd: true,
      proofPlaybackRestoreNotice: null,
      onCreateProofImport: () => {},
      onValidateLatestProofImport: () => {},
      onReviewPendingCrosswalks: () => {},
      onApproveLatestProofImport: () => {},
      onCreateProofRun: () => {},
      onRecomputeProofRunRisk: () => {},
      onActivateProofRun: () => {},
      onActivateProofSemester: () => {},
      onRetryProofRun: () => {},
      onArchiveProofRun: () => {},
      onRestoreProofSnapshot: () => {},
      onResetProofPlaybackSelection: () => {},
      onSelectProofCheckpoint: () => {},
      onStepProofPlayback: () => {},
      formatSplitSummary: (summary: unknown) => JSON.stringify(summary),
      formatKeyedCounts: (summary: unknown) => JSON.stringify(summary),
      formatHeadSupportSummary: (summary: unknown) => JSON.stringify(summary),
      formatDiagnosticSummary: (summary: unknown) => JSON.stringify(summary),
    }

    const { rerender } = render(createElement(SystemAdminProofDashboardWorkspace, {
      ...baseProps,
      proofDashboardLoading: false,
      initialActiveDashboardTab: 'checkpoint',
      activeRunCheckpoints: [selectedCheckpoint],
      selectedProofCheckpoint: selectedCheckpoint,
    }))

    expect(screen.getByRole('tab', { name: 'Checkpoint' }).getAttribute('aria-selected')).toBe('true')
    expect(screen.queryByText('Checkpoint Playback')).not.toBeNull()

    rerender(createElement(SystemAdminProofDashboardWorkspace, {
      ...baseProps,
      proofDashboardLoading: true,
      initialActiveDashboardTab: 'checkpoint',
      activeRunCheckpoints: [],
      selectedProofCheckpoint: null,
    }))

    await waitFor(() => {
      expect(screen.getByRole('tab', { name: 'Checkpoint' }).getAttribute('aria-selected')).toBe('true')
    })
    expect(screen.getByRole('tab', { name: 'Summary' }).getAttribute('aria-selected')).toBe('false')

    rerender(createElement(SystemAdminProofDashboardWorkspace, {
      ...baseProps,
      proofDashboardLoading: false,
      initialActiveDashboardTab: 'checkpoint',
      activeRunCheckpoints: [],
      selectedProofCheckpoint: null,
    }))

    await waitFor(() => {
      expect(screen.getByRole('tab', { name: 'Summary' }).getAttribute('aria-selected')).toBe('true')
    })
  })

  it('restores the previously selected proof dashboard tab after a remount', async () => {
    const selectedCheckpoint = buildCheckpoint({
      simulationStageCheckpointId: 'checkpoint_sem1_restore',
      semesterNumber: 1,
      stageKey: 'pre-tt1',
      stageLabel: 'Pre TT1',
      stageDescription: 'Persist the checkpoint tab between remounts.',
      stageOrder: 1,
      previousCheckpointId: null,
      nextCheckpointId: null,
      playbackAccessible: true,
      stageAdvanceBlocked: false,
      blockedByCheckpointId: null,
      blockedProgressionReason: null,
    })

    const proofDashboard: ApiProofDashboard = {
      imports: [],
      latestValidation: null,
      crosswalkReviewQueue: [],
      proofRuns: [],
      activeRunDetail: {
        simulationRunId: 'run_tab_restore',
        runLabel: 'Restore Tab Run',
        seed: 202,
        activeOperationalSemester: 1,
        createdAt: '2026-04-02T00:00:00.000Z',
        startedAt: '2026-04-02T00:00:00.000Z',
        completedAt: null,
        status: 'active',
        failureCode: null,
        failureMessage: null,
        progress: null,
        monitoringSummary: {
          riskAssessmentCount: 0,
          activeReassessmentCount: 0,
          alertDecisionCount: 0,
          acknowledgementCount: 0,
          resolutionCount: 0,
        },
        coverageDiagnostics: {
          behaviorProfileCoverage: { count: 1, expected: 1 },
          topicStateCoverage: { count: 1 },
          coStateCoverage: { count: 1 },
          questionTemplateCoverage: { count: 1 },
          questionResultCoverage: { count: 1 },
          interventionResponseCoverage: { count: 1 },
          worldContextCoverage: { count: 1 },
        },
        modelDiagnostics: {
          featureRowCount: 1,
          activeRunFeatureRowCount: 1,
          sourceRunCount: 1,
          production: null,
          challenger: null,
          correlations: null,
        },
        queueDiagnostics: {
          queuedRunCount: 0,
          runningRunCount: 0,
          failedRunCount: 0,
          retryableRunCount: 0,
          retryInFlightCount: 0,
          oldestQueuedRunAgeSeconds: 0,
          expiredLeaseRunCount: 0,
        },
        workerDiagnostics: null,
        checkpointReadiness: null,
        teacherAllocationLoad: [],
        queuePreview: [],
        snapshots: [],
        checkpoints: [selectedCheckpoint],
      },
      lifecycleAudit: [],
      recentOperationalEvents: [],
    }

    const baseProps = {
      proofDashboard,
      proofDashboardLoading: false,
      activeRunCheckpoints: [selectedCheckpoint],
      activeModelDiagnostics: null,
      activeProductionDiagnostics: null,
      activeDiagnosticsTrainingManifestVersion: null,
      activeDiagnosticsCalibrationVersion: null,
      activeDiagnosticsSplitSummary: null,
      activeDiagnosticsWorldSplitSummary: null,
      activeDiagnosticsScenarioFamilies: null,
      activeDiagnosticsHeadSupportSummary: null,
      activeDiagnosticsGovernedRunCount: null,
      activeDiagnosticsSkippedRunCount: null,
      activeDiagnosticsDisplayProbabilityAllowed: null,
      activeDiagnosticsSupportWarning: null,
      activeDiagnosticsPolicyDiagnostics: null,
      activeDiagnosticsCoEvidence: null,
      activeDiagnosticsPolicyAcceptance: null,
      activeDiagnosticsOverallCourseRuntime: null,
      activeDiagnosticsQueueBurden: null,
      activeDiagnosticsUiParity: null,
      selectedProofCheckpoint: selectedCheckpoint,
      selectedProofCheckpointDetail: null,
      selectedProofCheckpointBlocked: false,
      selectedProofCheckpointHasBlockedProgression: false,
      selectedProofCheckpointCanStepForward: true,
      selectedProofCheckpointCanPlayToEnd: true,
      proofPlaybackRestoreNotice: null,
      onCreateProofImport: () => {},
      onValidateLatestProofImport: () => {},
      onReviewPendingCrosswalks: () => {},
      onApproveLatestProofImport: () => {},
      onCreateProofRun: () => {},
      onRecomputeProofRunRisk: () => {},
      onActivateProofRun: () => {},
      onActivateProofSemester: () => {},
      onRetryProofRun: () => {},
      onArchiveProofRun: () => {},
      onRestoreProofSnapshot: () => {},
      onResetProofPlaybackSelection: () => {},
      onSelectProofCheckpoint: () => {},
      onStepProofPlayback: () => {},
      formatSplitSummary: (summary: unknown) => JSON.stringify(summary),
      formatKeyedCounts: (summary: unknown) => JSON.stringify(summary),
      formatHeadSupportSummary: (summary: unknown) => JSON.stringify(summary),
      formatDiagnosticSummary: (summary: unknown) => JSON.stringify(summary),
    }

    const firstMount = render(createElement(SystemAdminProofDashboardWorkspace, {
      ...baseProps,
      initialActiveDashboardTab: 'checkpoint',
    }))
    expect(screen.getByRole('tab', { name: 'Checkpoint' }).getAttribute('aria-selected')).toBe('true')
    firstMount.unmount()

    render(createElement(SystemAdminProofDashboardWorkspace, baseProps))

    await waitFor(() => {
      expect(screen.getByRole('tab', { name: 'Checkpoint' }).getAttribute('aria-selected')).toBe('true')
    })
    expect(screen.queryByText('Checkpoint Playback')).not.toBeNull()
  })

  it('renders explicit late-semester activation controls for semesters 4 through 6 and the final-stage checkpoint label', () => {
    const selectedCheckpoint = buildCheckpoint({
      simulationStageCheckpointId: 'checkpoint_sem6_post_see',
      semesterNumber: 6,
      stageKey: 'post-see',
      stageLabel: 'Post SEE',
      stageDescription: 'Final evidence checkpoint after SEE lands.',
      stageOrder: 3,
      previousCheckpointId: 'checkpoint_sem5_post_tt2',
      nextCheckpointId: null,
      playbackAccessible: true,
      stageAdvanceBlocked: false,
      blockedByCheckpointId: null,
      blockedProgressionReason: null,
      noActionHighRiskCount: 6,
      averageCounterfactualLiftScaled: 9,
    })
    const checkpoints = [
      buildCheckpoint({
        simulationStageCheckpointId: 'checkpoint_sem4_post_tt1',
        semesterNumber: 4,
        stageKey: 'post-tt1',
        stageLabel: 'Post TT1',
        stageDescription: 'Late-semester checkpoint after TT1 evidence lands.',
        stageOrder: 1,
        previousCheckpointId: null,
        nextCheckpointId: 'checkpoint_sem5_post_tt2',
        playbackAccessible: false,
        stageAdvanceBlocked: true,
        blockedByCheckpointId: 'checkpoint_sem4_post_tt1',
        blockedProgressionReason: 'Queue items from the semester-4 checkpoint remain unresolved.',
      }),
      buildCheckpoint({
        simulationStageCheckpointId: 'checkpoint_sem5_post_tt2',
        semesterNumber: 5,
        stageKey: 'post-tt2',
        stageLabel: 'Post TT2',
        stageDescription: 'Late-semester checkpoint after TT2 evidence lands.',
        stageOrder: 2,
        previousCheckpointId: 'checkpoint_sem4_post_tt1',
        nextCheckpointId: selectedCheckpoint.simulationStageCheckpointId,
        playbackAccessible: true,
        stageAdvanceBlocked: false,
        blockedByCheckpointId: null,
        blockedProgressionReason: null,
      }),
      selectedCheckpoint,
    ]

    const proofDashboard: ApiProofDashboard = {
      imports: [],
      latestValidation: null,
      crosswalkReviewQueue: [],
      proofRuns: [],
      activeRunDetail: {
        simulationRunId: 'run_001',
        runLabel: 'Proof Run 1',
        seed: 42,
        activeOperationalSemester: 6,
        createdAt: '2026-03-16T00:00:00.000Z',
        startedAt: '2026-03-16T00:00:00.000Z',
        completedAt: null,
        status: 'active',
        failureCode: null,
        failureMessage: null,
        progress: null,
        monitoringSummary: {
          riskAssessmentCount: 0,
          activeReassessmentCount: 0,
          alertDecisionCount: 0,
          acknowledgementCount: 0,
          resolutionCount: 0,
        },
        coverageDiagnostics: {
          behaviorProfileCoverage: { count: 1, expected: 1 },
          topicStateCoverage: { count: 1 },
          coStateCoverage: { count: 1 },
          questionTemplateCoverage: { count: 1 },
          questionResultCoverage: { count: 1 },
          interventionResponseCoverage: { count: 1 },
          worldContextCoverage: { count: 1 },
        },
        modelDiagnostics: {
          featureRowCount: 1,
          activeRunFeatureRowCount: 1,
          sourceRunCount: 1,
          production: null,
          challenger: null,
          correlations: null,
        },
        queueDiagnostics: {
          queuedRunCount: 0,
          runningRunCount: 0,
          failedRunCount: 0,
          retryableRunCount: 0,
          retryInFlightCount: 0,
          oldestQueuedRunAgeSeconds: 0,
          expiredLeaseRunCount: 0,
        },
        workerDiagnostics: null,
        checkpointReadiness: {
          totalCheckpointCount: checkpoints.length,
          readyCheckpointCount: 2,
          blockedCheckpointCount: 1,
          playbackBlockedCheckpointCount: 1,
          totalBlockingQueueItemCount: 5,
          firstBlockedCheckpointId: 'checkpoint_sem4_post_tt1',
          lastReadyCheckpointId: selectedCheckpoint.simulationStageCheckpointId,
        },
        teacherAllocationLoad: [],
        queuePreview: [],
        snapshots: [],
        checkpoints,
      },
      lifecycleAudit: [],
      recentOperationalEvents: [],
    }

    const markup = renderToStaticMarkup(createElement(SystemAdminProofDashboardWorkspace, {
      proofDashboard,
      proofDashboardLoading: false,
      activeRunCheckpoints: checkpoints,
      activeModelDiagnostics: null,
      activeProductionDiagnostics: null,
      activeDiagnosticsTrainingManifestVersion: null,
      activeDiagnosticsCalibrationVersion: null,
      activeDiagnosticsSplitSummary: null,
      activeDiagnosticsWorldSplitSummary: null,
      activeDiagnosticsScenarioFamilies: null,
      activeDiagnosticsHeadSupportSummary: null,
      activeDiagnosticsGovernedRunCount: null,
      activeDiagnosticsSkippedRunCount: null,
      activeDiagnosticsDisplayProbabilityAllowed: null,
      activeDiagnosticsSupportWarning: null,
      activeDiagnosticsPolicyDiagnostics: null,
      activeDiagnosticsCoEvidence: null,
      activeDiagnosticsPolicyAcceptance: null,
      activeDiagnosticsOverallCourseRuntime: null,
      activeDiagnosticsQueueBurden: null,
      activeDiagnosticsUiParity: null,
      selectedProofCheckpoint: selectedCheckpoint,
      selectedProofCheckpointDetail: null,
      selectedProofCheckpointBlocked: false,
      selectedProofCheckpointHasBlockedProgression: false,
      selectedProofCheckpointCanStepForward: false,
      selectedProofCheckpointCanPlayToEnd: false,
      proofPlaybackRestoreNotice: null,
      onCreateProofImport: () => {},
      onValidateLatestProofImport: () => {},
      onReviewPendingCrosswalks: () => {},
      onApproveLatestProofImport: () => {},
      onCreateProofRun: () => {},
      onRecomputeProofRunRisk: () => {},
      onActivateProofRun: () => {},
      onActivateProofSemester: () => {},
      onRetryProofRun: () => {},
      onArchiveProofRun: () => {},
      onRestoreProofSnapshot: () => {},
      onResetProofPlaybackSelection: () => {},
      onSelectProofCheckpoint: () => {},
      onStepProofPlayback: () => {},
      formatSplitSummary: summary => JSON.stringify(summary),
      formatKeyedCounts: summary => JSON.stringify(summary),
      formatHeadSupportSummary: summary => JSON.stringify(summary),
      formatDiagnosticSummary: summary => JSON.stringify(summary),
    }))

    expect(markup).toContain('data-proof-action="proof-activate-semester-4"')
    expect(markup).toContain('data-proof-action="proof-activate-semester-5"')
    expect(markup).toContain('data-proof-action="proof-activate-semester-6"')
    expect(markup).toContain('Sem 4')
    expect(markup).toContain('Sem 5')
    expect(markup).toContain('Sem 6')
    expect(markup).toContain('S4 · Post TT1 · blocked')
    expect(markup).toContain('S5 · Post TT2')
    expect(markup).toContain('S6 · Post SEE')
    expect(markup).toContain('No-Action Comparator')
    expect(markup).toContain('Average Counterfactual Lift')
  })

  it('renders playback-governed runtime diagnostics when no stored production artifact is active', () => {
    const selectedCheckpoint = buildCheckpoint({
      simulationStageCheckpointId: 'checkpoint_sem6_runtime_only',
      stageLabel: 'Post Assignments',
      stageKey: 'post-assignments',
      stageAdvanceBlocked: false,
      blockedByCheckpointId: null,
      blockedProgressionReason: null,
      playbackAccessible: true,
    })

    const proofDashboard: ApiProofDashboard = {
      imports: [],
      latestValidation: null,
      crosswalkReviewQueue: [],
      proofRuns: [],
      activeRunDetail: {
        simulationRunId: 'run_001',
        runLabel: 'Proof Run 1',
        seed: 42,
        activeOperationalSemester: 6,
        createdAt: '2026-03-16T00:00:00.000Z',
        startedAt: '2026-03-16T00:00:00.000Z',
        completedAt: null,
        status: 'active',
        failureCode: null,
        failureMessage: null,
        progress: null,
        monitoringSummary: {
          riskAssessmentCount: 120,
          activeReassessmentCount: 8,
          alertDecisionCount: 12,
          acknowledgementCount: 4,
          resolutionCount: 2,
        },
        coverageDiagnostics: {
          behaviorProfileCoverage: { count: 120, expected: 120 },
          topicStateCoverage: { count: 640 },
          coStateCoverage: { count: 310 },
          questionTemplateCoverage: { count: 84 },
          questionResultCoverage: { count: 2400 },
          interventionResponseCoverage: { count: 36 },
          worldContextCoverage: { count: 12 },
        },
        modelDiagnostics: {
          featureRowCount: 2400,
          activeRunFeatureRowCount: 360,
          sourceRunCount: 5,
          splitSummary: { train: 1800, validation: 300, test: 300 },
          worldSplitSummary: { train: 4, validation: 1, test: 1 },
          scenarioFamilySummary: { steady: 3, rescue: 2 },
          headSupportSummary: { overallCourseRisk: { positives: 1200 } },
          calibrationVersion: 'isotonic-v1',
          policyDiagnostics: { gates: 'ok' },
          coEvidenceDiagnostics: {
            totalRows: 360,
            fallbackCount: 40,
            byMode: {
              'offering-blueprint': 280,
              'rubric-derived': 40,
              'fallback-simulated': 40,
            },
          },
          uiParityDiagnostics: { facultySurface: 'aligned' },
          production: null,
          challenger: null,
          correlations: null,
        },
        queueDiagnostics: {
          queuedRunCount: 0,
          runningRunCount: 0,
          failedRunCount: 0,
          retryableRunCount: 0,
          retryInFlightCount: 0,
          oldestQueuedRunAgeSeconds: 0,
          expiredLeaseRunCount: 0,
        },
        workerDiagnostics: null,
        checkpointReadiness: null,
        teacherAllocationLoad: [],
        queuePreview: [],
        snapshots: [],
        checkpoints: [selectedCheckpoint],
      },
      lifecycleAudit: [],
      recentOperationalEvents: [],
    }

    const markup = renderToStaticMarkup(createElement(SystemAdminProofDashboardWorkspace, {
      proofDashboard,
      proofDashboardLoading: false,
      activeRunCheckpoints: [selectedCheckpoint],
      activeModelDiagnostics: { scenarioFamilySummary: { steady: 3, rescue: 2 } },
      activeProductionDiagnostics: null,
      activeDiagnosticsTrainingManifestVersion: 'manifest-v1',
      activeDiagnosticsCalibrationVersion: 'isotonic-v1',
      activeDiagnosticsSplitSummary: { train: 1800, validation: 300, test: 300 },
      activeDiagnosticsWorldSplitSummary: { train: 4, validation: 1, test: 1 },
      activeDiagnosticsScenarioFamilies: { steady: 3, rescue: 2 },
      activeDiagnosticsHeadSupportSummary: { overallCourseRisk: { positives: 1200 } },
      activeDiagnosticsGovernedRunCount: 5,
      activeDiagnosticsSkippedRunCount: 0,
      activeDiagnosticsDisplayProbabilityAllowed: false,
      activeDiagnosticsSupportWarning: 'Checkpoint support is runtime-governed until a production artifact is promoted.',
      activeDiagnosticsPolicyDiagnostics: { gates: 'ok' },
      activeDiagnosticsCoEvidence: {
        totalRows: 360,
        fallbackCount: 40,
        byMode: {
          'offering-blueprint': 280,
          'rubric-derived': 40,
          'fallback-simulated': 40,
        },
      },
      activeDiagnosticsPolicyAcceptance: { policy: 'accepted' },
      activeDiagnosticsOverallCourseRuntime: { parity: 'aligned' },
      activeDiagnosticsQueueBurden: { mentor: 2 },
      activeDiagnosticsUiParity: { facultySurface: 'aligned' },
      selectedProofCheckpoint: selectedCheckpoint,
      selectedProofCheckpointDetail: null,
      selectedProofCheckpointBlocked: false,
      selectedProofCheckpointHasBlockedProgression: false,
      selectedProofCheckpointCanStepForward: false,
      selectedProofCheckpointCanPlayToEnd: false,
      proofPlaybackRestoreNotice: null,
      onCreateProofImport: () => {},
      onValidateLatestProofImport: () => {},
      onReviewPendingCrosswalks: () => {},
      onApproveLatestProofImport: () => {},
      onCreateProofRun: () => {},
      onRecomputeProofRunRisk: () => {},
      onActivateProofRun: () => {},
      onActivateProofSemester: () => {},
      onRetryProofRun: () => {},
      onArchiveProofRun: () => {},
      onRestoreProofSnapshot: () => {},
      onResetProofPlaybackSelection: () => {},
      onSelectProofCheckpoint: () => {},
      onStepProofPlayback: () => {},
      formatSplitSummary: summary => JSON.stringify(summary),
      formatKeyedCounts: summary => JSON.stringify(summary),
      formatHeadSupportSummary: summary => JSON.stringify(summary),
      formatDiagnosticSummary: summary => JSON.stringify(summary),
    }))

    expect(markup).toContain('Playback-governed evidence')
    expect(markup).toContain('320/360 non-fallback evidence rows')
    expect(markup).toContain('No stored production artifact is active; this dashboard is reporting checkpoint-governed runtime diagnostics.')
    expect(markup).toContain('Runtime diagnostics are available for this run even though no stored evaluation artifact is active.')
    expect(markup).not.toContain('Heuristic fallback only')

    const { container } = render(createElement(SystemAdminProofDashboardWorkspace, {
      proofDashboard,
      proofDashboardLoading: false,
      initialActiveDashboardTab: 'diagnostics',
      activeRunCheckpoints: [selectedCheckpoint],
      activeModelDiagnostics: { scenarioFamilySummary: { steady: 3, rescue: 2 } },
      activeProductionDiagnostics: null,
      activeDiagnosticsTrainingManifestVersion: 'manifest-v1',
      activeDiagnosticsCalibrationVersion: 'isotonic-v1',
      activeDiagnosticsSplitSummary: { train: 1800, validation: 300, test: 300 },
      activeDiagnosticsWorldSplitSummary: { train: 4, validation: 1, test: 1 },
      activeDiagnosticsScenarioFamilies: { steady: 3, rescue: 2 },
      activeDiagnosticsHeadSupportSummary: { overallCourseRisk: { positives: 1200 } },
      activeDiagnosticsGovernedRunCount: 5,
      activeDiagnosticsSkippedRunCount: 0,
      activeDiagnosticsDisplayProbabilityAllowed: false,
      activeDiagnosticsSupportWarning: 'Checkpoint support is runtime-governed until a production artifact is promoted.',
      activeDiagnosticsPolicyDiagnostics: { gates: 'ok' },
      activeDiagnosticsCoEvidence: {
        totalRows: 360,
        fallbackCount: 40,
        byMode: {
          'offering-blueprint': 280,
          'rubric-derived': 40,
          'fallback-simulated': 40,
        },
      },
      activeDiagnosticsPolicyAcceptance: { policy: 'accepted' },
      activeDiagnosticsOverallCourseRuntime: { parity: 'aligned' },
      activeDiagnosticsQueueBurden: { mentor: 2 },
      activeDiagnosticsUiParity: { facultySurface: 'aligned' },
      selectedProofCheckpoint: selectedCheckpoint,
      selectedProofCheckpointDetail: null,
      selectedProofCheckpointBlocked: false,
      selectedProofCheckpointHasBlockedProgression: false,
      selectedProofCheckpointCanStepForward: false,
      selectedProofCheckpointCanPlayToEnd: false,
      proofPlaybackRestoreNotice: null,
      onCreateProofImport: () => {},
      onValidateLatestProofImport: () => {},
      onReviewPendingCrosswalks: () => {},
      onApproveLatestProofImport: () => {},
      onCreateProofRun: () => {},
      onRecomputeProofRunRisk: () => {},
      onActivateProofRun: () => {},
      onActivateProofSemester: () => {},
      onRetryProofRun: () => {},
      onArchiveProofRun: () => {},
      onRestoreProofSnapshot: () => {},
      onResetProofPlaybackSelection: () => {},
      onSelectProofCheckpoint: () => {},
      onStepProofPlayback: () => {},
      formatSplitSummary: summary => JSON.stringify(summary),
      formatKeyedCounts: summary => JSON.stringify(summary),
      formatHeadSupportSummary: summary => JSON.stringify(summary),
      formatDiagnosticSummary: summary => JSON.stringify(summary),
    }))

    expect(container.innerHTML).toContain('CO evidence mix: offering blueprint 280')
    expect(container.innerHTML).toContain('fallback simulated 40')
    expect(container.innerHTML).toContain('rubric derived 40')
  })

  it('routes explicit semester activation through the proof dashboard owner', () => {
    const onActivateProofSemester = vi.fn()
    const checkpoints = [
      buildCheckpoint({
        simulationStageCheckpointId: 'checkpoint_sem4',
        semesterNumber: 4,
        stageLabel: 'Semester 4',
        stageKey: 'post-tt1',
        stageOrder: 1,
        previousCheckpointId: null,
        nextCheckpointId: 'checkpoint_sem5',
        playbackAccessible: true,
        stageAdvanceBlocked: false,
        blockedByCheckpointId: null,
        blockedProgressionReason: null,
      }),
      buildCheckpoint({
        simulationStageCheckpointId: 'checkpoint_sem5',
        semesterNumber: 5,
        stageLabel: 'Semester 5',
        stageKey: 'post-tt2',
        stageOrder: 1,
        previousCheckpointId: 'checkpoint_sem4',
        nextCheckpointId: 'checkpoint_sem6',
        playbackAccessible: true,
        stageAdvanceBlocked: false,
        blockedByCheckpointId: null,
        blockedProgressionReason: null,
      }),
      buildCheckpoint({
        simulationStageCheckpointId: 'checkpoint_sem6',
        semesterNumber: 6,
        stageLabel: 'Semester 6',
        stageKey: 'post-see',
        stageOrder: 2,
        previousCheckpointId: 'checkpoint_sem5',
        nextCheckpointId: null,
        playbackAccessible: true,
        stageAdvanceBlocked: false,
        blockedByCheckpointId: null,
        blockedProgressionReason: null,
      }),
    ]

    const proofDashboard: ApiProofDashboard = {
      imports: [],
      latestValidation: null,
      crosswalkReviewQueue: [],
      proofRuns: [],
      activeRunDetail: {
        simulationRunId: 'run_001',
        runLabel: 'Proof Run 1',
        seed: 42,
        activeOperationalSemester: 6,
        createdAt: '2026-03-16T00:00:00.000Z',
        startedAt: '2026-03-16T00:00:00.000Z',
        completedAt: null,
        status: 'active',
        failureCode: null,
        failureMessage: null,
        progress: null,
        monitoringSummary: {
          riskAssessmentCount: 0,
          activeReassessmentCount: 0,
          alertDecisionCount: 0,
          acknowledgementCount: 0,
          resolutionCount: 0,
        },
        coverageDiagnostics: {
          behaviorProfileCoverage: { count: 1, expected: 1 },
          topicStateCoverage: { count: 1 },
          coStateCoverage: { count: 1 },
          questionTemplateCoverage: { count: 1 },
          questionResultCoverage: { count: 1 },
          interventionResponseCoverage: { count: 1 },
          worldContextCoverage: { count: 1 },
        },
        modelDiagnostics: {
          featureRowCount: 1,
          activeRunFeatureRowCount: 1,
          sourceRunCount: 1,
          production: null,
          challenger: null,
          correlations: null,
        },
        queueDiagnostics: {
          queuedRunCount: 0,
          runningRunCount: 0,
          failedRunCount: 0,
          retryableRunCount: 0,
          retryInFlightCount: 0,
          oldestQueuedRunAgeSeconds: 0,
          expiredLeaseRunCount: 0,
        },
        workerDiagnostics: null,
        checkpointReadiness: null,
        teacherAllocationLoad: [],
        queuePreview: [],
        snapshots: [],
        checkpoints,
      },
      lifecycleAudit: [],
      recentOperationalEvents: [],
    }

    render(createElement(SystemAdminProofDashboardWorkspace, {
      proofDashboard,
      proofDashboardLoading: false,
      activeRunCheckpoints: checkpoints,
      activeModelDiagnostics: null,
      activeProductionDiagnostics: null,
      activeDiagnosticsTrainingManifestVersion: null,
      activeDiagnosticsCalibrationVersion: null,
      activeDiagnosticsSplitSummary: null,
      activeDiagnosticsWorldSplitSummary: null,
      activeDiagnosticsScenarioFamilies: null,
      activeDiagnosticsHeadSupportSummary: null,
      activeDiagnosticsGovernedRunCount: null,
      activeDiagnosticsSkippedRunCount: null,
      activeDiagnosticsDisplayProbabilityAllowed: null,
      activeDiagnosticsSupportWarning: null,
      activeDiagnosticsPolicyDiagnostics: null,
      activeDiagnosticsCoEvidence: null,
      activeDiagnosticsPolicyAcceptance: null,
      activeDiagnosticsOverallCourseRuntime: null,
      activeDiagnosticsQueueBurden: null,
      activeDiagnosticsUiParity: null,
      selectedProofCheckpoint: null,
      selectedProofCheckpointDetail: null,
      selectedProofCheckpointBlocked: false,
      selectedProofCheckpointHasBlockedProgression: false,
      selectedProofCheckpointCanStepForward: true,
      selectedProofCheckpointCanPlayToEnd: true,
      proofPlaybackRestoreNotice: null,
      onCreateProofImport: () => {},
      onValidateLatestProofImport: () => {},
      onReviewPendingCrosswalks: () => {},
      onApproveLatestProofImport: () => {},
      onCreateProofRun: () => {},
      onRecomputeProofRunRisk: () => {},
      onActivateProofRun: () => {},
      onActivateProofSemester,
      onRetryProofRun: () => {},
      onArchiveProofRun: () => {},
      onRestoreProofSnapshot: () => {},
      onResetProofPlaybackSelection: () => {},
      onSelectProofCheckpoint: () => {},
      onStepProofPlayback: () => {},
      formatSplitSummary: summary => JSON.stringify(summary),
      formatKeyedCounts: summary => JSON.stringify(summary),
      formatHeadSupportSummary: summary => JSON.stringify(summary),
      formatDiagnosticSummary: summary => JSON.stringify(summary),
    }))

    const inactiveSemesterButton = document.querySelector('[data-proof-action="proof-activate-semester-5"]') as HTMLButtonElement | null
    const activeSemesterButton = document.querySelector('[data-proof-action="proof-activate-semester-6"]') as HTMLButtonElement | null

    expect(inactiveSemesterButton).toBeTruthy()
    expect(activeSemesterButton).toBeTruthy()

    expect(inactiveSemesterButton?.getAttribute('data-proof-action')).toBe('proof-activate-semester-5')
    expect(activeSemesterButton?.getAttribute('data-proof-action')).toBe('proof-activate-semester-6')
    expect(activeSemesterButton?.hasAttribute('disabled')).toBe(true)

    fireEvent.click(inactiveSemesterButton!)

    expect(onActivateProofSemester).toHaveBeenCalledTimes(1)
    expect(onActivateProofSemester).toHaveBeenCalledWith('run_001', 5)
  })
})
