"""Arctic invocation helper.

Arctic is the universal multi-provider CLI installed on this box. Our
executor delegates to `audit-map/16-scripts/arctic-session-wrapper.sh` for
the slot-isolated credential handling + caveman policy; this module adds:

  - post-run session-id recovery by matching `--title <task-tag>`
  - session export to JSON for validator consumption
  - briefing packer: summarise a prior task's session JSON into a
    markdown briefing that can be `--file`-attached to the next task.

Arctic's behaviour under non-TTY:
  - `arctic run --title T ...` writes all messages to
    `$XDG_DATA_HOME/arctic/storage/session/<projectID>/ses_*.json`
  - stdout is only the TUI spinner; it is NOT a complete transcript.
  - `arctic session list` prints a table of (sessionID, title, updated).
  - `arctic export <ses_id>` emits the full session as JSON on stdout.

We rely on `--title` as our correlation key because session IDs are
generated by arctic and unknown before the run.
"""
from __future__ import annotations

import json
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
ARCTIC_WRAPPER = REPO_ROOT / "audit-map" / "16-scripts" / "arctic-session-wrapper.sh"

# Regex for `arctic session list` row: first column is `ses_<hex>` followed by whitespace, then title.
_SESS_ROW_RE = re.compile(r"^\s*(ses_[A-Za-z0-9]+)\s{2,}(.*?)\s{2,}")


@dataclass
class ArcticRun:
    session_id: str | None
    transcript: str            # concatenated assistant text (for marker extraction)
    exit_code: int
    log_path: Path | None


def build_invocation(
    *,
    slot: str,
    model_ref: str | None,
    title: str,
    bundle_path: Path,
    briefing_path: Path | None = None,
    profile: str = "safe",
    format_: str = "default",
) -> list[str]:
    """Return argv that invokes the audit-map arctic wrapper for `slot`.

    The wrapper handles XDG isolation, credential seeding, and caveman
    policy. We pass `AUDIT_PROMPT_VERBATIM=1` via the environment (see
    `executor._write_wrapper`) to prevent the wrapper from wrapping our
    prompt bundle.
    """
    argv: list[str] = [
        "bash", str(ARCTIC_WRAPPER),
        "--method", "run",
        "--slot", slot,
        "--format", format_,
        "--message-file", str(bundle_path),
    ]
    if model_ref:
        argv += ["--model", model_ref]
    # Extra arctic flags we need beyond what the wrapper supports are
    # passed verbatim after `--` (the wrapper forwards unknown tail args
    # to `arctic run`).
    argv.append("--")
    argv += ["--title", title, "--profile", profile]
    if briefing_path and Path(briefing_path).is_file():
        argv += ["--file", str(briefing_path)]
    return argv


def find_session_by_title(slot: str, title: str) -> str | None:
    """Scan `arctic session list` for a title match and return its ses_id.

    We need the slot so we can run arctic under the right XDG store.
    """
    cmd = [
        "bash", "-lc",
        (
            f"source audit-map/16-scripts/_audit-common.sh && "
            f"run_arctic_for_slot {slot} session list 2>&1"
        ),
    ]
    try:
        out = subprocess.check_output(cmd, cwd=str(REPO_ROOT), timeout=30)
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired):
        return None
    txt = out.decode("utf-8", errors="replace")
    for line in txt.splitlines():
        m = _SESS_ROW_RE.match(line)
        if not m:
            continue
        ses_id, row_title = m.group(1), m.group(2).strip()
        if row_title == title or row_title.startswith(title):
            return ses_id
    return None


def export_session_json(slot: str, session_id: str) -> dict | None:
    cmd = [
        "bash", "-lc",
        (
            f"source audit-map/16-scripts/_audit-common.sh && "
            f"run_arctic_for_slot {slot} export {session_id} 2>/dev/null"
        ),
    ]
    try:
        out = subprocess.check_output(cmd, cwd=str(REPO_ROOT), timeout=60)
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired):
        return None
    try:
        return json.loads(out.decode("utf-8", errors="replace"))
    except json.JSONDecodeError:
        return None


def transcript_from_session(session_json: dict) -> str:
    """Concat every assistant message's text content in order."""
    if not isinstance(session_json, dict):
        return ""
    parts = []
    msgs = session_json.get("messages") or []
    for msg in msgs:
        if not isinstance(msg, dict):
            continue
        role = msg.get("role") or (msg.get("info") or {}).get("role")
        if role != "assistant":
            continue
        for part in msg.get("parts") or []:
            if not isinstance(part, dict):
                continue
            t = part.get("text") or part.get("content")
            if t:
                parts.append(str(t))
        # fallback: flat "content" field
        flat = msg.get("content")
        if isinstance(flat, str) and flat:
            parts.append(flat)
    return "\n\n".join(parts)


def recover(slot: str, title: str) -> tuple[str | None, str]:
    """Locate session by title then return (session_id, concat_transcript)."""
    sid = find_session_by_title(slot, title)
    if not sid:
        return None, ""
    j = export_session_json(slot, sid) or {}
    return sid, transcript_from_session(j)
